hledger -f examples/1ktxns-1accts.journal     balance
hledger -f examples/1ktxns-10accts.journal    balance
hledger -f examples/1ktxns-100accts.journal   balance
hledger -f examples/1ktxns-1kaccts.journal    balance
hledger -f examples/1ktxns-10kaccts.journal   balance
hledger -f examples/1ktxns-100kaccts.journal  balance
hledger -f examples/1ktxns-1maccts.journal    balance
hledger -f examples/10ktxns-1accts.journal    balance
hledger -f examples/10ktxns-10accts.journal   balance
hledger -f examples/10ktxns-100accts.journal  balance
hledger -f examples/10ktxns-1kaccts.journal   balance
hledger -f examples/10ktxns-10kaccts.journal  balance
hledger -f examples/10ktxns-100kaccts.journal balance
hledger -f examples/10ktxns-1maccts.journal   balance
