hledger -f examples/1ktxns-1kaccts.journal  balance
hledger -f examples/2ktxns-1kaccts.journal  balance
hledger -f examples/3ktxns-1kaccts.journal  balance
hledger -f examples/4ktxns-1kaccts.journal  balance
hledger -f examples/5ktxns-1kaccts.journal  balance
hledger -f examples/6ktxns-1kaccts.journal  balance
hledger -f examples/7ktxns-1kaccts.journal  balance
hledger -f examples/8ktxns-1kaccts.journal  balance
hledger -f examples/9ktxns-1kaccts.journal  balance
hledger -f examples/10ktxns-1kaccts.journal balance
hledger -f examples/20ktxns-1kaccts.journal balance
hledger -f examples/30ktxns-1kaccts.journal balance
hledger -f examples/40ktxns-1kaccts.journal balance
hledger -f examples/50ktxns-1kaccts.journal balance
hledger -f examples/60ktxns-1kaccts.journal balance
hledger -f examples/70ktxns-1kaccts.journal balance
hledger -f examples/80ktxns-1kaccts.journal balance
hledger -f examples/90ktxns-1kaccts.journal balance
hledger -f examples/100ktxns-1kaccts.journal balance
