# stack build plan using GHC 9.2.4

resolver: nightly-2022-08-14

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web

extra-deps:
# for hledger-lib:
# for hledger:
# for hledger-ui:
- brick-1.0
# for hledger-web:
# for Shake.hs:

nix:
  pure: false
  packages: [perl gmp ncurses zlib]

# # for precise profiling, per https://www.tweag.io/posts/2020-01-30-haskell-profiling.html:
# # apply-ghc-options: everything
# # rebuild-ghc-options: true
# # stack build --profile --ghc-options="-fno-prof-auto"

# # tell GHC to write hie files, eg for weeder. Rumoured to be slow.
# # ghc-options:
# #   "$locals": -fwrite-ide-info

# # ghc-options:
# #   "$locals": -ddump-timings
# #  "$targets": -Werror
# #  "$everything": -O2
# #  some-package: -DSOME_CPP_FLAG
