# stack build plan using GHC 8.2.1
# keep synced with download.md ?

resolver: nightly-2017-09-07

extra-deps:
- wai-handler-launch-3.0.2.3

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api