# stack build plan using GHC 9.12.2
# https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.12
# https://downloads.haskell.org/ghc/9.12.1/docs/users_guide/9.12.1-notes.html
# https://downloads.haskell.org/ghc/9.12.2/docs/users_guide/9.12.2-notes.html

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web

resolver: nightly-2025-09-30

notify-if-ghc-untested:   false
notify-if-cabal-untested: false

extra-deps:
# currently out of stackage:
- yesod-static-1.6.1.0
- yesod-test-1.6.19
- cryptonite-0.30
- cryptonite-conduit-0.2.2

nix:
  pure: false
  packages: [perl gmp ncurses zlib]

# ghc-options:
#   "$locals": -Wno-x-partial
#   "$locals": -fplugin Debug.Breakpoint

# # for precise profiling, per https://www.tweag.io/posts/2020-01-30-haskell-profiling.html:
# # apply-ghc-options: everything
# # rebuild-ghc-options: true
# # stack build --profile --ghc-options="-fno-prof-auto"

# # tell GHC to write hie files, eg for weeder. Rumoured to be slow.
# # ghc-options:
# #   "$locals": -fwrite-ide-info

# # ghc-options:
# #   "$locals": -ddump-timings
# #  "$targets": -Werror
# #  "$everything": -O2
# #  some-package: -DSOME_CPP_FLAG
