# stack build plan using GHC 8.2.1

resolver: nightly-2017-12-14

nix:
  enable: false
  pure: false
  packages: [perl gmp ncurses zlib]

# extra-deps:

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api
