# cf https://github.com/commercialhaskell/stack/wiki/stack.yaml

resolver: lts-3.0

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web

flags:

extra-deps:
- brick-0.2
- text-zipper-0.2.1
- vty-5.3.1
