# stack build plan using GHC 9.10.1
# https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.10
# https://downloads.haskell.org/ghc/9.10.1/docs/users_guide/9.10.1-notes.html

resolver: nightly-2024-09-26
compiler: ghc-9.10.1
notify-if-ghc-untested: false
notify-if-cabal-untested: false

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web

extra-deps:
- base-compat-0.14.0
- base-compat-batteries-0.14.0
# for hledger-lib
- Cabal-3.12.0.0
- Cabal-syntax-3.12.0.0
- directory-1.3.8.3@rev:3
- filepath-1.4.300.2
#- filepath-1.5.3.0    # not accepted for hledger-lib for some reason
- ghc-boot-9.10.1@rev:1
- process-1.6.24.0
- unix-2.8.5.1
# for windows
- Win32-2.14.0.0
- time-1.12.2

# for hledger
- haskeline-0.8.2.1
# to silence a warning
- wizards-1.0.3@rev:3

# for dev builds when the ghcdebug flag is enabled:
- ghc-debug-convention-0.6.0.0
- ghc-debug-stub-0.6.0.0

nix:
  pure: false
  packages: [perl gmp ncurses zlib]

# ghc-options:
#   "$locals": -Wno-x-partial
#   "$locals": -fplugin Debug.Breakpoint

# # for precise profiling, per https://www.tweag.io/posts/2020-01-30-haskell-profiling.html:
# # apply-ghc-options: everything
# # rebuild-ghc-options: true
# # stack build --profile --ghc-options="-fno-prof-auto"

# # tell GHC to write hie files, eg for weeder. Rumoured to be slow.
# # ghc-options:
# #   "$locals": -fwrite-ide-info

# # ghc-options:
# #   "$locals": -ddump-timings
# #  "$targets": -Werror
# #  "$everything": -O2
# #  some-package: -DSOME_CPP_FLAG
