# stack build plan using GHC 9.14
# https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.14

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web

resolver: nightly-2026-04-17
compiler: ghc-9.14
# notify-if-ghc-untested:   false
# notify-if-cabal-untested: false
notify-if-no-run-tests:   false
# for hledger-web and https://haskell.github.io/security-advisories/advisory/HSEC-2026-0007.html
extra-deps:
- aeson-2.3.0.0
- text-iso8601-0.2.0.0
allow-newer: true
