# default stack build plan for developers/HEAD users.
# This should normally use a recent stackage nightly,
# to help us detect problems at stackage.

resolver: nightly-2018-03-10

nix:
  pure: false
  packages: [perl gmp ncurses zlib]

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api

extra-deps:
- easytest-0.1
