# this or a newer snapshot is suggested (hledger-api/servant/aeson requires > lts-5)
resolver: lts-6.8

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api

#flags:

extra-deps:
- brick-0.8

# https://docs.haskellstack.org/en/stable/yaml_configuration/
