# stack build plan using GHC 8.2.x

resolver: lts-10.0

nix:
  enable: false
  pure: false
  packages: [perl gmp ncurses zlib]

# extra-deps:

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api
