# stack build plan using GHC 8.2.x

resolver: lts-10.3

nix:
  enable: false
  pure: false
  packages: [perl gmp ncurses zlib]

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api

extra-deps:
# for tools/easytest.hs. Should be harmless otherwise.
- git: git@github.com:joelburget/easytest.git
  commit: 5d5b851e77368071b5727cd366af9c6ecd288add
