# stack build plan using GHC 8.8.3

nix:
  pure: false
  packages: [perl gmp ncurses zlib]

resolver: lts-16.9

# Provides a very nice reduction in final binary size.
ghc-options:
  $everything: -split-sections

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web

# extra-deps:
# for hledger-lib:
# for hledger:
# for hledger-ui:
# for hledger-web:
# for Shake.hs:

# for precise profiling, per https://www.tweag.io/posts/2020-01-30-haskell-profiling.html:
# apply-ghc-options: everything
# rebuild-ghc-options: true
# stack build --profile --ghc-options="-fno-prof-auto"

# tell GHC to write hie files, eg for weeder. Rumoured to be slow.
# ghc-options:
#   "$locals": -fwrite-ide-info
