# stack build plan using GHC 9.6.3

resolver: lts-22.4

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web

# extra-deps:

nix:
  pure: false
  packages: [perl gmp ncurses zlib]

# ghc-options:
#   "$locals": -fplugin Debug.Breakpoint

# # for precise profiling, per https://www.tweag.io/posts/2020-01-30-haskell-profiling.html:
# # apply-ghc-options: everything
# # rebuild-ghc-options: true
# # stack build --profile --ghc-options="-fno-prof-auto"

# # tell GHC to write hie files, eg for weeder. Rumoured to be slow.
# # ghc-options:
# #   "$locals": -fwrite-ide-info

# # ghc-options:
# #   "$locals": -ddump-timings
# #  "$targets": -Werror
# #  "$everything": -O2
# #  some-package: -DSOME_CPP_FLAG
extra-deps:
  - vty-windows-0.2.0.1

