# stack build plan using GHC 9.8.2

resolver: nightly-2024-09-04

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web

extra-deps:
# needed only for dev builds when the ghcdebug flag is enabled:
- ghc-debug-convention-0.6.0.0
- ghc-debug-stub-0.6.0.0

nix:
  pure: false
  packages: [perl gmp ncurses zlib]

# ghc-options:
#   "$locals": -Wno-x-partial
#   "$locals": -fplugin Debug.Breakpoint

# # for precise profiling, per https://www.tweag.io/posts/2020-01-30-haskell-profiling.html:
# # apply-ghc-options: everything
# # rebuild-ghc-options: true
# # stack build --profile --ghc-options="-fno-prof-auto"

# # tell GHC to write hie files, eg for weeder. Rumoured to be slow.
# # ghc-options:
# #   "$locals": -fwrite-ide-info

# # ghc-options:
# #   "$locals": -ddump-timings
# #  "$targets": -Werror
# #  "$everything": -O2
# #  some-package: -DSOME_CPP_FLAG
