# stack build plan using GHC 8.6.4

resolver: nightly-2019-03-09

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api

nix:
  pure: false
  packages: [perl gmp ncurses zlib]

# allow-newer: true

extra-deps:
# hledger-lib:
# hledger:
# hledger-ui:
# hledger-web:
# hledger-api:

# Workaround for https://github.com/commercialhaskell/stack/issues/3922:
- haskell-src-exts-1.21.0

# Workaround for https://github.com/simonmichael/hledger/issues/1039 (hledger-web on Windows 7):
- github: kazu-yamamoto/unix-time
  commit: cdfda676dcc1ee84b3de5dca4a48945f2d6b6e10
