name: hledger-api
version: '1.3.99'
synopsis: Web API server for the hledger accounting tool
description: |
  This is a simple web API server for hledger data.
  It comes with a series of simple client-side web app examples.

  hledger is a cross-platform program for tracking money, time, or
  any other commodity, using double-entry accounting and a simple,
  editable file format. It is inspired by and largely compatible
  with ledger(1).  hledger provides command-line, curses and web
  interfaces, and aims to be a reliable, practical tool for daily
  use.
category: Finance
license: GPL-3
author: Simon Michael <simon@joyful.com>
maintainer: Simon Michael <simon@joyful.com>
github: simonmichael/hledger
homepage: http://hledger.org
bug-reports: http://bugs.hledger.org
stability: alpha
tested-with: GHC==7.10.3, GHC==8.0.2, GHC==8.2.1

extra-source-files:
- CHANGES
- README
- examples/*.html

data-files:
- doc/hledger-api.1
- doc/hledger-api.1.txt
- doc/hledger-api.1.info

dependencies:
- hledger-lib >= 1.3.99 && < 1.4
- hledger >= 1.3.99 && < 1.4
- base >=4.8 && <5
- aeson
- bytestring
- containers
- Decimal
- docopt
- either
- microlens >=0.4 && <0.5
- microlens-platform >=0.2.3.1 && <0.4
- safe
- servant-server >= 0.10
- servant-swagger
- swagger2 >= 2.0 && < 2.2
- text
- transformers
- wai
- wai-extra
- warp

executables:
  hledger-api:
    main: hledger-api.hs
    ghc-options: -threaded
    cpp-options: -DVERSION="1.3.99"
