name        : hledger-ui
version     : '1.9.99'
synopsis    : Curses-style user interface for the hledger accounting tool
description : |
  This is hledger's curses-style interface.
  It is simpler and more convenient for browsing data than the command-line interface,
  but lighter and faster than hledger-web.

  hledger is a cross-platform program for tracking money, time, or
  any other commodity, using double-entry accounting and a simple,
  editable file format. It is inspired by and largely compatible
  with ledger(1).  hledger provides command-line, curses and web
  interfaces, and aims to be a reliable, practical tool for daily
  use.
category    : Finance, Console
license     : GPL-3
author      : Simon Michael <simon@joyful.com>
maintainer  : Simon Michael <simon@joyful.com>
github      : simonmichael/hledger
homepage    : http://hledger.org
bug-reports : http://bugs.hledger.org
stability   : stable
tested-with : GHC==7.10.3, GHC==8.0.2, GHC==8.2.2

extra-source-files:
  - CHANGES
  - README
  - hledger-ui.1
  - hledger-ui.txt
  - hledger-ui.info

#data-files:

flags:
  threaded:
    description: Build with support for multithreaded execution
    manual: false
    default: true

cpp-options: -DVERSION="1.9.99"

dependencies:
 - hledger >=1.9.99 && <2.0
 - hledger-lib >=1.9.99 && <2.0
 - ansi-terminal >=0.6.2.3
 - async
 - base >=4.8 && <4.12
 - base-compat >=0.8.1
 - cmdargs >=0.8
 - containers
 - data-default
 - directory
 - filepath
 - fsnotify >=0.2
 - HUnit
 - microlens >=0.4
 - microlens-platform >=0.2.3.1
 - megaparsec >=6.4.1
 - pretty-show >=1.6.4
 - process >=1.2
 - safe >=0.2
 - split >=0.1
 - text >=1.2
 - text-zipper >=0.4
 - time >=1.5
 - transformers
 - vector

when:
 # curses is required to build terminfo for vty for hledger-ui.
 # On POSIX systems it might be not present.
 # On windows it's very likely not present, but possibly it could be.
 # Ideally we'd like to
 # on POSIX: give a clear error ("install your system libcurses-dev package") if not present
 # on windows: quietly skip building if not present, build if it is present
 #  curses
 #    default: True
 #    description:
 # For now, just don't build hledger-ui on windows
 - condition: os(windows)
   then:
     buildable: false
   else:
     dependencies:
       - brick >=0.12
       - vty >=5.5

executables:
  hledger-ui:
    source-dirs: .
    main: hledger-ui.hs
    ghc-options:
      -Wall
      -fno-warn-unused-do-bind
      -fno-warn-name-shadowing
      -fno-warn-missing-signatures
      -fno-warn-type-defaults
      -fno-warn-orphans
    when:
    - condition: flag(threaded)
      ghc-options: -threaded
