name:          hledger-ui
version: 1.50.99
license:       GPL-3.0-or-later
maintainer:    Simon Michael <simon@joyful.com>
author:        Simon Michael <simon@joyful.com>
stability:     stable
tested-with:   ghc==9.6.7, ghc==9.8.4, ghc==9.10.2, ghc==9.12.2
homepage:      http://hledger.org
bug-reports:   http://bugs.hledger.org
github:        simonmichael/hledger
category:      Finance, Console
synopsis:      Terminal interface for the hledger accounting system
description: |
  A simple terminal user interface for the hledger accounting system.
  It can be a more convenient way to browse your accounts than the CLI.
  
  hledger is a robust, cross-platform set of tools for tracking money,
  time, or any other commodity, using double-entry accounting and a
  simple, editable file format, with command-line, terminal and web
  interfaces. It is a Haskell rewrite of Ledger, and one of the leading
  implementations of Plain Text Accounting. Read more at:
  <https://hledger.org>

extra-source-files:
- CHANGES.md
- README.md
- hledger-ui.1
- hledger-ui.txt
- hledger-ui.info

flags:
  threaded:
    description: Build with support for multithreaded execution
    default: true
    manual:  false
  debug:
    description: Build with GHC 9.10+ stack traces enabled
    default: false
    manual:  true
#  ghcdebug:
#    description: Build with support for attaching a ghc-debug client
#    default: false
#    manual:  true

dependencies:
- base >=4.18 && <4.22

cpp-options: -DVERSION="1.50.99"

language: GHC2021

ghc-options:
- -Wall
- -Wno-incomplete-uni-patterns
- -Wno-missing-signatures
- -Wno-orphans
- -Wno-type-defaults
- -Wno-unused-do-bind

when:

- condition: (flag(debug))
  cpp-options: -DDEBUG

# - condition: (flag(ghcdebug))
#   cpp-options: -DGHCDEBUG
#   dependencies:
#   - ghc-debug-stub >=0.6.0.0 && <0.7

library:
  source-dirs: .
  # default: All modules in source-dirs less other-modules less modules mentioned in when
  # exposed-modules:
  dependencies:
  - hledger-lib >=1.50.99 && <1.51
  - hledger >=1.50.99 && <1.51
  - ansi-terminal >=0.9
  - async
  - cmdargs >=0.8
  - containers >=0.5.9
  - data-default
  - directory
  - doclayout >=0.3 && <0.6
  - extra >=1.7.11
  - filepath
  - fsnotify >=0.4.2.0 && <0.5
  - githash >=0.1.6.2
  - microlens >=0.4
  - microlens-platform >=0.2.3.1
  - megaparsec >=7.0.0 && <9.8
  - mtl >=2.2.1
  - process >=1.2
  - safe >=0.3.20
  - split >=0.1
  - stm
  - text >=1.2.4.1
  - text-zipper >=0.4
  - time >=1.5
  - transformers
  - vector
  - brick >=2.1.1 && <2.3.2 || >2.3.2 && < 2.10
  - vty >=6.1 && <6.5
  - vty-crossplatform >= 0.4.0.0 && < 0.5.0.0
  when:
    - condition: os(windows)
      then:
        dependencies: vty-windows >= 0.2.0.1 && < 0.3.0.0
      else:
        dependencies: unix

executables:
  hledger-ui:
    source-dirs: app
    main: hledger-ui.hs
    when:
    - condition: flag(threaded)
      ghc-options: -threaded
    dependencies:
    - hledger-ui
