# hpack specification for generating the cabal file
# https://github.com/sol/hpack#readme
# http://www.haskell.org/cabal/release/cabal-latest/doc/users-guide/authors.html
#
# as of hpack 0.5.4 these must be added manually:
# - tested-with
# - flags
# - benchmarks
# - conditional blocks

name        : hledger-lib
version     : '0.26.98'
stability   : stable
category    : Finance, Console
synopsis    : Core data types, parsers and utilities for the hledger accounting tool.
description : |
  hledger is a library and set of user tools for working
  with financial data (or anything that can be tracked in a
  double-entry accounting ledger.) It is a haskell port and
  friendly fork of John Wiegley's Ledger. hledger provides
  command-line, curses and web interfaces, and aims to be a
  reliable, practical tool for daily use.

license     : GPL
author      : Simon Michael <simon@joyful.com>
maintainer  : Simon Michael <simon@joyful.com>
github      : simonmichael/hledger
homepage    : http://hledger.org
bug-reports : http://bugs.hledger.org
# XXX not supported
tested-with : GHC==7.4.2, GHC==7.6.3, GHC==7.8.4, GHC==7.10.1
            
extra-source-files:
  - CHANGES

# XXX not supported
# flag double
#     description:   Use old Double number representation (instead of Decimal), for testing/benchmarking.
#     default:       False
#     manual:        True
#
# flag old-locale
#   description: A compatibility flag, set automatically by cabal.
#                If false then depend on time >= 1.5, 
#                if true then depend on time < 1.5 together with old-locale.
#   default: False

dependencies:
  - base >= 4.3 && < 5
  - base-compat >= 0.8.1
  - array
  - blaze-markup >= 0.5.1
  - bytestring
  - cmdargs >= 0.10 && < 0.11
  - containers
  - csv
  - Decimal
  - deepseq
  - directory
  - filepath
  - mtl
  - mtl-compat
  - old-time
  - parsec >= 3
  - regex-tdfa
  - safe >= 0.2
  - split >= 0.1 && < 0.3
  - transformers >= 0.2 && < 0.5
  - utf8-string >= 0.3.5 && < 1.1
  - HUnit
# XXX not supported
# if impl(ghc >= 7.4)
#   dependencies: pretty-show >= 1.6.4
# if flag(old-locale)
#   build-depends: time < 1.5, old-locale
# else
#   build-depends: time >= 1.5
  - pretty-show >= 1.6.4
  - time >= 1.5

ghc-options:
  -Wall
  -fno-warn-unused-do-bind
  -fno-warn-name-shadowing
  -fno-warn-missing-signatures
  -fno-warn-type-defaults
  -fno-warn-orphans

library:
  # XXX not supported
  # if flag(double)
  #   cpp-options: -DDOUBLE
  # source-dirs: .  # XXX includes Setup and uncommitted stuff
  exposed-modules:
    - Hledger
    - Hledger.Data
    - Hledger.Data.Account
    - Hledger.Data.AccountName
    - Hledger.Data.Amount
    - Hledger.Data.Commodity
    - Hledger.Data.Dates
    - Hledger.Data.Journal
    - Hledger.Data.Ledger
    - Hledger.Data.OutputFormat
    - Hledger.Data.Posting
    - Hledger.Data.RawOptions
    - Hledger.Data.TimeLog
    - Hledger.Data.Transaction
    - Hledger.Data.Types
    - Hledger.Query
    - Hledger.Read
    - Hledger.Read.CsvReader
    - Hledger.Read.JournalReader
    - Hledger.Read.TimelogReader
    - Hledger.Reports
    - Hledger.Reports.ReportOptions
    - Hledger.Reports.BalanceHistoryReport
    - Hledger.Reports.BalanceReport
    - Hledger.Reports.EntriesReport
    - Hledger.Reports.MultiBalanceReports
    - Hledger.Reports.PostingsReport
    - Hledger.Reports.TransactionsReports
    - Hledger.Utils
    - Hledger.Utils.Debug
    - Hledger.Utils.Regex
    - Hledger.Utils.UTF8IOCompat

tests:
  tests:
    main: suite.hs
    source-dirs: tests
    dependencies:
      - hledger-lib
      - test-framework
      - test-framework-hunit
