{-|

A 'Posting' represents a change (by some 'MixedAmount') of the balance in
some 'Account'.  Each 'Transaction' contains two or more postings which
should add up to 0. Postings reference their parent transaction, so we can
look up the date or description there.

-}

{-# LANGUAGE CPP #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE OverloadedStrings #-}

module Hledger.Data.Posting (
  -- * Posting
  nullposting,
  posting,
  post,
  vpost,
  post',
  vpost',
  nullassertion,
  balassert,
  balassertTot,
  balassertParInc,
  balassertTotInc,
  -- * operations
  originalPosting,
  postingStatus,
  isReal,
  isVirtual,
  isBalancedVirtual,
  isEmptyPosting,
  hasBalanceAssignment,
  hasAmount,
  isExplicitAmount,
  postingAllTags,
  transactionAllTags,
  relatedPostings,
  postingStripCosts,
  postingApplyAliases,
  postingApplyCommodityStyles,
  postingStyleAmounts,
  postingAddTags,
  postingAddHiddenAndMaybeVisibleTag,
  -- * date operations
  postingDate,
  postingDate2,
  postingDateOrDate2,
  -- * account name operations
  accountNamesFromPostings,
  -- * comment/tag operations
  commentJoin,
  commentAddTag,
  commentAddTagUnspaced,
  commentAddTagNextLine,
  commentPrependTag,
  generatedTransactionTagName,
  modifiedTransactionTagName,
  generatedPostingTagName,
  feesplitPostingTagName,
  lotsplitPostingTagName,
  lotParentAssertionTagName,
  postingHasTag,
  costPostingTagName,
  conversionPostingTagName,

  -- * arithmetic
  sumPostings,
  postingNegate,
  postingNegateMainAmount,
  -- * rendering
  showPosting,
  showPostingLines,
  postingAsLines,
  postingsAsLines,
  postingsAsLinesWithLayout,
  postingIndent,
  showAccountName,
  renderCommentLines,
  showBalanceAssertion,
  balanceAssertionOperatorB,
  balanceAssertionAmountB,
  PostingLayout(..),
  defaultPostingLayout,
  defaultDecimalMarkColumn,
  PostingWidths(..),
  AmountCols(..),
  amountIntegerWidth,
  -- * misc.
  postingTransformAmount,
  postingApplyValuation,
  postingToCost,
  postingAddInferredEquityPostings,
  postingPriceDirectivesFromCost,
  postingCommodities,
  tests_Posting
)
where

import Data.Default (def)
import Data.Foldable (asum)
import Data.Function ((&))
import Data.Map qualified as M
import Data.Maybe (fromMaybe, isJust, mapMaybe)
import Data.List (sort, union)
#if !MIN_VERSION_base(4,20,0)
import Data.List (foldl')
#endif
import Data.Set qualified as S
import Data.Text (Text)
import Data.Text qualified as T
import Data.Text.Lazy qualified as TL
import Data.Text.Lazy.Builder qualified as TB
import Data.Time.Calendar (Day)
import Safe (maximumBound)
import Text.DocLayout (realLength)
import Text.Tabular.AsciiWide hiding (render)

import Hledger.Utils
import Hledger.Data.Types
import Hledger.Data.Amount
import Hledger.Data.AccountName
import Hledger.Data.Dates (nulldate)
import Hledger.Data.Valuation


-- | Special tags hledger sometimes adds to mark various things.
-- These should be hidden tag names, beginning with _.
-- With --verbose-tags, the equivalent visible tags will also be added.
-- These tag names are mentioned in docs and can be matched by user queries, so consider the impact before changing them.
generatedTransactionTagName, modifiedTransactionTagName, costPostingTagName, conversionPostingTagName, generatedPostingTagName, feesplitPostingTagName, lotsplitPostingTagName, lotParentAssertionTagName :: TagName
generatedTransactionTagName = "_generated-transaction"  -- transactions generated by a periodic txn rule
modifiedTransactionTagName  = "_modified-transaction"   -- transactions modified by an auto posting rule
generatedPostingTagName     = "_generated-posting"      -- postings generated by hledger for one reason or another
costPostingTagName          = "_cost-posting"           -- postings which have or could have a cost that's equivalent to nearby conversion postings
conversionPostingTagName    = "_conversion-posting"     -- postings to an equity account of Conversion type which have an amount that's equivalent to a nearby costful or potentially costful posting
feesplitPostingTagName      = "_feesplit-posting"       -- a synthetic posting carved off an existing posting by lot transfer auto-split (the priced fee fragment); hidden by default in print
lotsplitPostingTagName      = "_lotsplit-posting"       -- a tail fragment from a per-lot split, dropped when collapsing to the user's original form
lotParentAssertionTagName   = "_lot-parent-assertion"   -- a synthetic zero-amount posting on the parent account, carrying a balance assertion relocated from a posting that was split into lot subaccounts

-- | True if the posting has a tag with the given name (hidden or visible).
postingHasTag :: TagName -> Posting -> Bool
postingHasTag name p = any ((==name) . fst) (ptags p)

instance HasAmounts BalanceAssertion where
  styleAmounts styles ba@BalanceAssertion{baamount} = ba{baamount=styleAmounts styles baamount}

instance HasAmounts Posting where
  styleAmounts styles p@Posting{pamount, pbalanceassertion} =
    p{ pamount=styleAmounts styles pamount
      ,pbalanceassertion=styleAmounts styles pbalanceassertion 
      }

{-# DEPRECATED postingApplyCommodityStyles "please use styleAmounts instead" #-}
-- | Find and apply the appropriate display style to the posting amounts
-- in each commodity (see journalCommodityStyles).
-- Main amount precisions may be set or not according to the styles, but cost precisions are not set.
postingApplyCommodityStyles :: M.Map CommoditySymbol AmountStyle -> Posting -> Posting
postingApplyCommodityStyles = styleAmounts

{-# DEPRECATED postingStyleAmounts "please use styleAmounts instead" #-}
-- | Like postingApplyCommodityStyles, but neither
-- main amount precisions or cost precisions are set.
postingStyleAmounts :: M.Map CommoditySymbol AmountStyle -> Posting -> Posting
postingStyleAmounts = styleAmounts

nullposting, posting :: Posting
nullposting = Posting
                {pdate=Nothing
                ,pdate2=Nothing
                ,pstatus=Unmarked
                ,paccount=""
                ,pamount=nullmixedamt
                ,pcomment=""
                ,preal=RealPosting
                ,ptags=[]
                ,pbalanceassertion=Nothing
                ,ptransaction=Nothing
                ,poriginal=Nothing
                }
posting = nullposting

-- constructors

-- | Make a posting to an account.
post :: AccountName -> Amount -> Posting
post acc amt = posting {paccount=acc, pamount=mixedAmount amt}

-- | Make a virtual (unbalanced) posting to an account.
vpost :: AccountName -> Amount -> Posting
vpost acc amt = (post acc amt){preal=VirtualPosting}

-- | Make a posting to an account, maybe with a balance assertion.
post' :: AccountName -> Amount -> Maybe BalanceAssertion -> Posting
post' acc amt ass = posting {paccount=acc, pamount=mixedAmount amt, pbalanceassertion=ass}

-- | Make a virtual (unbalanced) posting to an account, maybe with a balance assertion.
vpost' :: AccountName -> Amount -> Maybe BalanceAssertion -> Posting
vpost' acc amt ass = (post' acc amt ass){preal=VirtualPosting, pbalanceassertion=ass}

nullassertion :: BalanceAssertion
nullassertion = BalanceAssertion
                  {baamount=nullamt
                  ,batotal=False
                  ,bainclusive=False
                  ,baposition=initialPos ""
                  }

-- | Make a partial, exclusive balance assertion.
balassert :: Amount -> Maybe BalanceAssertion
balassert amt = Just $ nullassertion{baamount=amt}

-- | Make a total, exclusive balance assertion.
balassertTot :: Amount -> Maybe BalanceAssertion
balassertTot amt = Just $ nullassertion{baamount=amt, batotal=True}

-- | Make a partial, inclusive balance assertion.
balassertParInc :: Amount -> Maybe BalanceAssertion
balassertParInc amt = Just $ nullassertion{baamount=amt, bainclusive=True}

-- | Make a total, inclusive balance assertion.
balassertTotInc :: Amount -> Maybe BalanceAssertion
balassertTotInc amt = Just $ nullassertion{baamount=amt, batotal=True, bainclusive=True}

-- | Render the balance-assertion operator glyph: \"=\", \"==\", \"=*\", or \"==*\".
balanceAssertionOperatorB :: BalanceAssertion -> WideBuilder
balanceAssertionOperatorB ba =
    singleton '=' <> eq <> ast
  where
    eq  = if batotal ba     then singleton '=' else mempty
    ast = if bainclusive ba then singleton '*' else mempty
    singleton c = WideBuilder (TB.singleton c) 1

-- | Render a balance assertion's expected amount, using the given AmountFormat.
balanceAssertionAmountB :: AmountFormat -> BalanceAssertion -> WideBuilder
balanceAssertionAmountB fmt = showAmountB fmt . baamount

-- | Render a balance assertion, as the =[=][*] symbol and expected amount,
-- separated by a single space. Used by the legacy hledger 1.x layout path;
-- the decimal-aligned path renders the operator and amount separately so it
-- can pad between them.
showBalanceAssertion :: BalanceAssertion -> WideBuilder
showBalanceAssertion ba =
    balanceAssertionOperatorB ba
    <> WideBuilder (TB.singleton ' ') 1
    <> balanceAssertionAmountB def{displayZeroCommodity=True, displayForceDecimalMark=True} ba

-- Get the original posting, if any.
originalPosting :: Posting -> Posting
originalPosting p = fromMaybe p $ poriginal p

showPosting :: Posting -> String
showPosting p = T.unpack . T.unlines $ postingsAsLines defaultFmt False [p]

-- | How posting lines should be aligned by 'postingsAsLines' / 'showTransaction'.
data PostingLayout
  = LayoutHledger1            -- ^ Right-align amounts in a 12+-char field, as in hledger 1.x.
  | LayoutDecimal !Int        -- ^ Align the first decimal mark of each amount at the given target column.
  deriving (Eq, Show)

-- | Default visible column (1-indexed) where posting amount decimal marks
-- should be aligned in `print` output. Used as the target unless a
-- transaction's account names + amount widths force amounts further right.
defaultDecimalMarkColumn :: Int
defaultDecimalMarkColumn = 53

-- | Default posting layout: decimal-mark alignment at column 'defaultDecimalMarkColumn'.
defaultPostingLayout :: PostingLayout
defaultPostingLayout = LayoutDecimal defaultDecimalMarkColumn

-- | Visible-character widths derived from one posting, for cross-posting
-- alignment in 'postingsAsLinesDecimal'. All fields are independent of
-- layout (decimalcol etc.), so they can be safely consumed inside the
-- lazy knot that decides those columns.
data PostingWidths = PostingWidths
  { pwAcct     :: !Int
    -- ^ Account-name visible width. Used to size the account/status field
    --   so all postings' account names line up.
  , pwLeft     :: !Int
    -- ^ Main amount's integer-side width: characters from the start of the
    --   rendered amount up to (but not including) the decimal mark.
    --   Includes any L-side commodity prefix (e.g. \"$\") and sign.
    --   Computed by 'amountIntegerWidth'. For a multi-commodity amount
    --   rendered on multiple lines, this is the max across rows.
    --   Used to position the decimal mark column.
  , pwRight    :: !Int
    -- ^ Main amount's post-decimal width: characters from the decimal mark
    --   (inclusive) to the end of the rendered amount, including any cost
    --   annotation (\"\@ 1.20 USD\") and any R-side commodity suffix.
    --   Equivalent to @wbWidth wb - lw@ per amount row, taken as the max
    --   across rows. Used to position the assertion @=@ column one space
    --   past the rightmost amount.
  , pwOperator   :: !Int
    -- ^ Visible width of this posting's balance-assertion operator:
    --   1 (@=@), 2 (@==@ or @=*@), 3 (@==*@), or 0 if the posting has no
    --   @pbalanceassertion@. Used to position the assertion-amount column
    --   one space past the widest operator.
  , pwAsnLeft  :: !Int
    -- ^ Assertion amount's integer-side width, computed via
    --   'amountIntegerWidth' on @baamount@ with the same display options
    --   used for the main amount. 0 if no assertion. Used to decimal-align
    --   the assertion amounts.
  }
  deriving (Eq, Show)

-- | The three target columns derived in the knot of 'postingsAsLinesDecimal'
-- and consumed by 'postingAsLines' for aligning the main amount, the @=@ glyph,
-- and the assertion amount. @acEquals@ and @acAssDecMark@ are 0 when no posting in
-- the group has a balance assertion (in which case the renderer never
-- consults them).
data AmountCols = AmountCols
  { acDecMark    :: !Int  -- ^ Column for the main amount's decimal mark.
  , acEquals     :: !Int  -- ^ Column for the first @=@ of the balance assertion/assignment.
  , acAssDecMark :: !Int  -- ^ Column for the assertion amount's decimal mark.
  }
  deriving (Eq, Show)

-- | Visible width of the part of a rendered amount that appears before its
-- (real or virtual) decimal mark — i.e. from the start of the amount through
-- the last digit of the integer portion (including any L-side commodity
-- prefix). Computed structurally from the 'Amount' data rather than by
-- parsing the rendered text, so it is unaffected by trailing cost annotations,
-- lot syntax, comments, or digits that may appear inside a commodity name.
-- Used to align integer-ends across postings at decimalcol-1.
amountIntegerWidth :: AmountFormat -> Amount -> Int
amountIntegerWidth opts a
    -- The "AUTO" commodity marks a missing amount; showAmountB renders it as
    -- empty, so its left-width is 0.
    | acommodity a == "AUTO" = 0
    | otherwise              = commodityPrefixW + quantityIntegerW
  where
    s = astyle a
    -- Width of the integer portion of the rendered quantity. Renders the amount
    -- truncated to integer with precision 0; the result has no decimal mark or
    -- fractional digits, so its width is exactly sign + integer-digits + group-seps.
    -- Sign is added explicitly to handle the -0.x → 0 truncation case — but only
    -- when the rendered amount will actually show a sign (i.e., it has fractional
    -- digits). At Precision 0 a value rounding to 0 shows as "0" with no sign,
    -- so no extra slot is reserved.
    quantityIntegerW =
        let intAmt   = a{ aquantity = fromInteger (truncate (aquantity a) :: Integer)
                        , astyle    = s{asprecision = Precision 0}
                        }
            w        = wbWidth (showAmountQuantity False intAmt)
            showsFractional = case asprecision s of
                Precision 0 -> False
                _           -> True
            signLost = aquantity a < 0 && (truncate (aquantity a) :: Integer) == 0
                    && showsFractional
        in w + (if signLost then 1 else 0)
    -- Width of the commodity portion when it appears as a prefix (L-side).
    commodityPrefixW
      | ascommodityside s == L =
          let comm   = (if displayQuotes opts then quoteCommoditySymbolIfNeeded else id) (acommodity a)
              spaceW = if not (T.null comm) && ascommodityspaced s then 1 else 0
          in realLength comm + spaceW
      | otherwise = 0

-- | Visible width of a posting's status prefix (e.g. \"* \" or \"! \"), or 0
-- if it has no status flag. Used to compute account-field width per transaction.
postingStatusWidth :: Posting -> Int
postingStatusWidth p = case pstatus p of
    Unmarked -> 0
    _        -> 2

-- | Render a posting, at the appropriate width for aligning with
-- its siblings if any. Used by the rewrite command.
showPostingLines :: Posting -> [Text]
showPostingLines p = fst $ postingAsLines defaultFmt False False maxstatuswidth maxacctwidth dc p
  where
    siblings = maybe [p] tpostings $ ptransaction p
    linesWithWidths = map (postingAsLines defaultFmt False False maxstatuswidth maxacctwidth dc) siblings
    maxstatuswidth = maximumBound 0 $ map postingStatusWidth siblings
    pws = map snd linesWithWidths
    maxacctwidth   = maximumBound 0 $ map pwAcct    pws
    maxleftwidth   = maximumBound 0 $ map pwLeft    pws
    maxrightwidth  = maximumBound 0 $ map pwRight   pws
    maxoperatorwidth = maximumBound 0 $ map pwOperator  pws
    maxasnleftwidth = maximumBound 0 $ map pwAsnLeft pws
    decimalcol    = max defaultDecimalMarkColumn (maxacctwidth + maxstatuswidth + 7 + maxleftwidth)
    eqcol         = decimalcol + maxrightwidth + 1
    asndecimalcol = eqcol + maxoperatorwidth + 1 + maxasnleftwidth
    dc = AmountCols decimalcol eqcol asndecimalcol

-- | Render a transaction's postings as indented lines, suitable for `print` output,
-- using the default posting layout (decimal-mark alignment at column 53).
--
-- Normally these will be in valid journal syntax which hledger can reparse
-- (though they may include no-longer-valid balance assertions).
-- Explicit amounts are shown, implicit amounts are not.
--
-- Postings with multicommodity explicit amounts are handled as follows:
-- if onelineamounts is true, these amounts are shown on one line,
-- comma-separated, and the output will not be valid journal syntax.
-- Otherwise, they are shown as several similar postings, one per commodity.
-- When the posting has a balance assertion, it is attached to the last of these postings.
--
-- Note: a few fields of the caller's @AmountFormat@ are overridden internally;
-- see 'postingAsLines' for details.
--
postingsAsLines :: AmountFormat -> Bool -> [Posting] -> [Text]
postingsAsLines basefmt onelineamounts =
    postingsAsLinesWithLayout basefmt onelineamounts defaultPostingLayout

-- | Like 'postingsAsLines' but with an explicit 'PostingLayout': either the
-- new decimal-mark alignment (with a target column) or the older hledger 1.x
-- right-aligned layout.
postingsAsLinesWithLayout :: AmountFormat -> Bool -> PostingLayout -> [Posting] -> [Text]
postingsAsLinesWithLayout basefmt onelineamounts layout ps = case layout of
    LayoutDecimal targetcol -> postingsAsLinesDecimal basefmt onelineamounts targetcol ps
    LayoutHledger1          -> postingsAsLinesHledger1 basefmt onelineamounts ps

-- | Decimal-mark-aligned layout (the new default). The target column is bumped
-- right per-transaction if needed to keep at least 2 spaces between each
-- account name and amount.
postingsAsLinesDecimal :: AmountFormat -> Bool -> Int -> [Posting] -> [Text]
postingsAsLinesDecimal basefmt onelineamounts targetcol ps = concatMap fst linesWithWidths
  where
    -- Lazy knot: postingAsLines takes the layout columns (AmountCols) and
    -- returns this posting's PostingWidths; the layout columns are computed
    -- from the cross-posting maxes of those widths. This terminates only
    -- because PostingWidths fields do NOT depend on AmountCols — they are
    -- structural widths of the posting's amount/account/assertion data, while
    -- AmountCols only affects the rendered text (the first element of each
    -- linesWithWidths pair, which we don't force until concatMap fst above).
    -- If any PostingWidths field ever started depending on AmountCols this
    -- would diverge. Keep that invariant when changing postingAsLines.
    linesWithWidths = map (postingAsLines basefmt False onelineamounts maxstatuswidth maxacctwidth dc) ps
    maxstatuswidth = maximumBound 0 $ map postingStatusWidth ps
    pws = map snd linesWithWidths
    maxacctwidth    = maximumBound 0 $ map pwAcct    pws
    maxleftwidth    = maximumBound 0 $ map pwLeft    pws
    maxrightwidth   = maximumBound 0 $ map pwRight   pws
    maxoperatorwidth  = maximumBound 0 $ map pwOperator  pws
    maxasnleftwidth = maximumBound 0 $ map pwAsnLeft pws
    decimalcol    = max targetcol (maxacctwidth + maxstatuswidth + 7 + maxleftwidth)
    -- eqcol / asndecimalcol are 0 (and unused by the renderer) when no
    -- posting in the group has a balance assertion.
    hasAssertion  = maxoperatorwidth > 0
    eqcol         = if hasAssertion then decimalcol + maxrightwidth + 1 else 0
    asndecimalcol = if hasAssertion then eqcol + maxoperatorwidth + 1 + maxasnleftwidth else 0
    dc            = AmountCols decimalcol eqcol asndecimalcol

-- | hledger 1.x layout: right-align amounts within a 12+-char field, lifted
-- verbatim from the pre-decimal-alignment code. Kept as an escape hatch for
-- users who prefer the old appearance via @print --layout=hledger1@.
postingsAsLinesHledger1 :: AmountFormat -> Bool -> [Posting] -> [Text]
postingsAsLinesHledger1 basefmt onelineamounts ps = concatMap first3 linesWithWidths
  where
    linesWithWidths = map (postingAsLinesHledger1 basefmt False onelineamounts maxacctwidth maxamtwidth) ps
    maxacctwidth = maximumBound 0 $ map second3 linesWithWidths
    maxamtwidth  = maximumBound 0 $ map third3 linesWithWidths

-- | hledger 1.x per-posting renderer: right-aligned amounts.
-- This is the pre-decimal-alignment 'postingAsLines' body, restored verbatim.
postingAsLinesHledger1 :: AmountFormat -> Bool -> Bool -> Int -> Int -> Posting -> ([Text], Int, Int)
postingAsLinesHledger1 basefmt elideamount onelineamounts acctwidth amtwidth p =
    (concatMap (++ newlinecomments) postingblocks, thisacctwidth, thisamtwidth)
  where
    postingblocks = [map T.stripEnd . T.lines . TL.toStrict $
                       render [ textCell BottomLeft statusandaccount
                              , textCell BottomLeft "  "
                              , Cell BottomLeft [pad amt]
                              , Cell BottomLeft [assertion]
                              , textCell BottomLeft samelinecomment
                              ]
                    | (amt,assertion) <- shownAmountsAssertions]
    render = renderRow def{tableBorders=False, borderSpaces=False} . Group NoLine . map Header
    pad amt = WideBuilder (TB.fromText $ T.replicate w " ") w <> amt
      where w = max 12 amtwidth - wbWidth amt  -- min. 12 for backwards compatibility

    pacctstr p' = showAccountName Nothing (preal p') (paccount p')
    pstatusandacct p' = pstatusprefix p' <> pacctstr p'
    pstatusprefix p' = case pstatus p' of
        Unmarked -> ""
        s        -> T.pack (show s) <> " "

    -- prices are considered part of the amount string when right-aligning amounts.
    -- The knot between amtwidth and thisamtwidth is tied via lazy evaluation, so
    -- thisamtwidth must not depend on amtwidth.
    shownAmounts
      | elideamount = [mempty]
      | otherwise   = showMixedAmountLinesB displayopts $ pamount p
      where displayopts = basefmt{
          displayZeroCommodity=True, displayForceDecimalMark=True, displayOneLine=onelineamounts
          }
    thisamtwidth = maximumBound 0 $ map wbWidth shownAmounts

    shownAmountsAssertions = zip shownAmounts shownAssertions
      where
        shownAssertions = replicate (length shownAmounts - 1) mempty ++ [assertion]
        assertion = maybe mempty ((WideBuilder (TB.singleton ' ') 1 <>).showBalanceAssertion) $ pbalanceassertion p

    statusandaccount = postingIndent . fitText (Just $ 2 + acctwidth) Nothing False True $ pstatusandacct p
    thisacctwidth = realLength $ pacctstr p

    (samelinecomment, newlinecomments) =
      case renderCommentLines (pcomment p) of []   -> ("",[])
                                              c:cs -> (c,cs)

-- | Render one posting, on one or more lines, suitable for `print` output.
-- Also returns the 'PostingWidths' computed from this posting's structural
-- data (account name, main amount, assertion operator / amount), used by the
-- caller's lazy knot to derive the layout columns.
--
-- There will be an indented account name, plus one or more of status flag,
-- posting amount, balance assertion, same-line comment, next-line comments.
--
-- If the posting's amount is implicit or if elideamount is true, no amount is shown.
-- If the posting's amount is explicit and multi-commodity, multiple similar
-- postings are shown, one for each commodity, to help produce parseable journal syntax.
-- Or if onelineamounts is true, such amounts are shown on one line, comma-separated
-- (and the output will not be valid journal syntax).
--
-- If an amount is zero, any commodity symbol attached to it is shown
-- (and the corresponding commodity display style is used).
--
-- Three target columns are supplied via 'AmountCols':
--
-- * @acDecMark@ — the main amount's decimal mark is left-padded to land here.
--   With multi-commodity postings rendered on multiple lines, every line is
--   aligned at this column. Callers (postingsAsLines, showPostingLines) pick
--   it so that at least 2 spaces remain between the widest account name and
--   the start of the amount area.
-- * @acEquals@ — the first @=@ of any balance-assertion operator (@=@, @==@, @=*@,
--   or @==*@) is padded to land here, one space past the rightmost main
--   amount across all postings.
-- * @acAssDecMark@ — the assertion amount's decimal mark is padded to land
--   here. The leftmost assertion amount starts one space past the widest
--   operator; narrower-operator postings get extra space so all assertion
--   amounts line up on their decimals.
--
-- @acEquals@ and @acAssDecMark@ are unused (and may be 0) when no posting in the
-- group has a balance assertion.
--
-- Note: this function overrides four fields of the caller's @AmountFormat@:
--
-- * @displayZeroCommodity = True@ — always show the commodity on zero amounts
--   so they participate in alignment.
-- * @displayForceDecimalMark = True@ — force a decimal mark when digit groups
--   are shown, for unambiguous display.
-- * @displayOneLine = onelineamounts@ — driven by this function's parameter.
-- * @displayMinWidth = Nothing@ — disable the legacy right-alignment of
--   multi-commodity amount lines, since this function provides its own
--   decimal-mark alignment.
--
postingAsLines :: AmountFormat -> Bool -> Bool -> Int -> Int -> AmountCols -> Posting -> ([Text], PostingWidths)
postingAsLines basefmt elideamount onelineamounts statuswidth acctwidth dc p =
    (concatMap (++ newlinecomments) postingblocks, widths)
  where
    AmountCols{acDecMark=decimalcol, acEquals=eqcol, acAssDecMark=asndecimalcol} = dc

    widths = PostingWidths
      { pwAcct     = thisacctwidth
      , pwLeft     = thisleftwidth
      , pwRight    = thisrightwidth
      , pwOperator = thisoperatorwidth
      , pwAsnLeft  = thisasnleftwidth
      }

    -- This needs to be converted to strict Text in order to strip trailing
    -- spaces. This adds a small amount of inefficiency, and the only difference
    -- is whether there are trailing spaces in print (and related) reports. This
    -- could be removed and we could just keep everything as a Text Builder, but
    -- would require adding trailing spaces to 42 failing tests.
    postingblocks = [map T.stripEnd . T.lines . TL.toStrict $
                       render [ textCell BottomLeft statusandaccount
                              , textCell BottomLeft "  "
                              , Cell BottomLeft [padLeft (decimalcol - acctwidth - statuswidth - 7 - lw) amt]
                              , Cell BottomLeft [asn]
                              , textCell BottomLeft samelinecomment
                              ]
                    | (amt, lw, asn) <- amountAssertionRows]
    render = renderRow def{tableBorders=False, borderSpaces=False} . Group NoLine . map Header

    -- Prepend N space characters to a WideBuilder; N is floored at 0.
    -- The amount area starts at column (acctwidth + statuswidth + 7) (1-indexed):
    -- 4 indent + (statuswidth + acctwidth) status/account field + 2 separator.
    -- For the main amount, a pre-decimal width lw means we want the decimal
    -- at column (acctwidth + statuswidth + 7 + lw + N), so N =
    -- decimalcol - (acctwidth + statuswidth + 7 + lw).
    padLeft n b = WideBuilder (TB.fromText $ T.replicate w " ") w <> b
      where w = max 0 n

    pacctstr p' = showAccountName Nothing (preal p') (paccount p')
    pstatusandacct p' = pstatusprefix p' <> pacctstr p'
    pstatusprefix p' = case pstatus p' of
        Unmarked -> ""
        s        -> T.pack (show s) <> " "

    -- Display options used to render BOTH the main amount and the assertion
    -- amount, so their lw / rw computations match the rendered text and the
    -- two amounts share commodity styling within a transaction.
    -- See postingAsLines's haddock for which fields of basefmt are overridden.
    displayopts = basefmt{
        displayZeroCommodity    = True
      , displayForceDecimalMark = True
      , displayOneLine          = onelineamounts
      , displayMinWidth         = Nothing
      }

    -- Per-amount-row triples (wb, lw, rw): the rendered builder, its
    -- integer-side visible width left of the decimal, and its post-decimal
    -- visible width (rw = wbWidth wb - lw). All structural; must remain
    -- independent of any layout column (see the lazy knot in
    -- postingsAsLinesDecimal).
    amountRows
      | elideamount = [(mempty, 0, 0)]
      | otherwise   = case showMixedAmountLinesPartsB displayopts (pamount p) of
                        [] -> [(mempty, 0, 0)]
                        xs -> [ (wb, lw, wbWidth wb - lw)
                              | (wb, a) <- xs
                              , let lw = amountIntegerWidth displayopts a]

    thisleftwidth   = maximumBound 0 [lw | (_, lw, _) <- amountRows]
    thisrightwidth  = maximumBound 0 [rw | (_, _, rw) <- amountRows]

    -- Per-posting balance-assertion widths (0 if the posting has no assertion).
    (thisoperatorwidth, thisasnleftwidth) = case pbalanceassertion p of
        Nothing -> (0, 0)
        Just ba -> ( wbWidth (balanceAssertionOperatorB ba)
                   , amountIntegerWidth displayopts (baamount ba)
                   )

    -- The balance-assertion cell on the last amount row (if there's an
    -- assertion). Lays out as: pad1 + operator + pad2 + amount, where pad1
    -- lifts the operator to eqcol and pad2 lifts the assertion amount's
    -- decimal mark to asndecimalcol. By construction in the knot, pad1 and
    -- pad2 are >= 1 when any sibling has the maximum value; floor at 1
    -- defensively in case of a single-posting context with no cross-sibling
    -- alignment to satisfy.
    assertionWB = case pbalanceassertion p of
        Nothing -> mempty
        Just ba ->
          let pad1Len = max 1 (eqcol - decimalcol - thisrightwidth)
              pad2Len = max 1 (asndecimalcol - eqcol - thisoperatorwidth - thisasnleftwidth)
          in padLeft pad1Len (balanceAssertionOperatorB ba)
             <> padLeft pad2Len (balanceAssertionAmountB displayopts ba)

    -- Pair each amount row with its assertion (only on the last row).
    amountAssertionRows =
        [(wb, lw, asn) | ((wb, lw, _), asn) <- zip amountRows shownAssertions]
      where
        shownAssertions = replicate (length amountRows - 1) mempty ++ [assertionWB]

    -- pad to the maximum account name width, plus statuswidth chars to leave
    -- room for status flags (where any sibling has one), to keep amounts aligned
    statusandaccount = postingIndent . fitText (Just $ statuswidth + acctwidth) Nothing False True $ pstatusandacct p
    thisacctwidth = realLength $ pacctstr p

    (samelinecomment, newlinecomments) =
      case renderCommentLines (pcomment p) of []   -> ("",[])
                                              c:cs -> (c,cs)

-- | Show an account name, clipped to the given width if any, and
-- appropriately bracketed/parenthesised for the given posting realness.
showAccountName :: Maybe Int -> PostingRealness -> AccountName -> Text
showAccountName w = fmt
  where
    fmt RealPosting            = maybe id T.take w
    fmt VirtualPosting         = wrap "(" ")" . maybe id (T.takeEnd . subtract 2) w
    fmt BalancedVirtualPosting = wrap "[" "]" . maybe id (T.takeEnd . subtract 2) w

-- | Render a transaction or posting's comment as indented, semicolon-prefixed comment lines.
-- The first line (unless empty) will have leading space, subsequent lines will have a larger indent.
renderCommentLines :: Text -> [Text]
renderCommentLines t =
  case T.lines t of
    []      -> []
    [l]     -> [commentSpace $ comment l]        -- single-line comment
    ("":ls) -> "" : map (postingIndent . comment) ls  -- multi-line comment with empty first line
    (l:ls)  -> commentSpace (comment l) : map (postingIndent . comment) ls
  where
    comment = ("; "<>)

-- | Prepend a suitable indent for a posting (or transaction/posting comment) line.
postingIndent :: Text -> Text
postingIndent = ("    "<>)

-- | Prepend the space required before a same-line comment.
commentSpace :: Text -> Text
commentSpace = ("  "<>)


isReal :: Posting -> Bool
isReal p = preal p == RealPosting

isVirtual :: Posting -> Bool
isVirtual p = preal p == VirtualPosting

isBalancedVirtual :: Posting -> Bool
isBalancedVirtual p = preal p == BalancedVirtualPosting

hasAmount :: Posting -> Bool
hasAmount = not . isMissingMixedAmount . pamount

-- | Was this posting's amount explicitly written by the user, rather than
-- inferred by hledger ? Amounts inferred from a balance assignment are
-- also counted as explicit, since they are the same as what the user wrote.
-- Inferred postings are recognised by their preserved original posting having a missing amount.
isExplicitAmount :: Posting -> Bool
isExplicitAmount p =
  let orig = originalPosting p
  in not (isMissingMixedAmount (pamount orig)) || isJust (pbalanceassertion orig)

hasBalanceAssignment :: Posting -> Bool
hasBalanceAssignment p = not (hasAmount p) && isJust (pbalanceassertion p)

-- | Sorted unique account names referenced by these postings.
accountNamesFromPostings :: [Posting] -> [AccountName]
accountNamesFromPostings = S.toList . S.fromList . map paccount

-- | Sum all amounts from a list of postings.
sumPostings :: [Posting] -> MixedAmount
sumPostings = foldl' (\amt p -> maPlus amt $ pamount p) nullmixedamt

-- | Negate the posting's main amount and balance assertion amount if any.
postingNegate :: Posting -> Posting
postingNegate p@Posting{pamount=a, pbalanceassertion=mb} =
  p{pamount=negate a, pbalanceassertion=fmap balanceAssertionNegate mb}
  where
    balanceAssertionNegate b@BalanceAssertion{baamount=ba} = b{baamount=negate ba}

-- | Negate the posting's main amount but not the balance assertion amount.
postingNegateMainAmount :: Posting -> Posting
postingNegateMainAmount p@Posting{pamount=a} = p{pamount=negate a}

-- | Strip all prices from a Posting.
postingStripCosts :: Posting -> Posting
postingStripCosts = postingTransformAmount mixedAmountStripCosts

-- | Get a posting's (primary) date - it's own primary date if specified,
-- otherwise the parent transaction's primary date, or the null date if
-- there is no parent transaction.
postingDate :: Posting -> Day
postingDate p = fromMaybe nulldate $ asum dates
    where dates = [ pdate p, tdate <$> ptransaction p ]

-- | Get a posting's secondary (secondary) date, which is the first of:
-- posting's secondary date, transaction's secondary date, posting's
-- primary date, transaction's primary date, or the null date if there is
-- no parent transaction.
postingDate2 :: Posting -> Day
postingDate2 p = fromMaybe nulldate $ asum dates
  where dates = [ pdate2 p
                , tdate2 =<< ptransaction p
                , pdate p
                , tdate <$> ptransaction p
                ]

-- | Get a posting's primary or secondary date, as specified.
postingDateOrDate2 :: WhichDate -> Posting -> Day
postingDateOrDate2 PrimaryDate   = postingDate
postingDateOrDate2 SecondaryDate = postingDate2

-- | Get a posting's status. This is cleared or pending if those are
-- explicitly set on the posting, otherwise the status of its parent
-- transaction, or unmarked if there is no parent transaction. (Note
-- the ambiguity, unmarked can mean "posting and transaction are both
-- unmarked" or "posting is unmarked and don't know about the transaction".
postingStatus :: Posting -> Status
postingStatus Posting{pstatus=s, ptransaction=mt} = case s of
    Unmarked -> maybe Unmarked tstatus mt
    _ -> s

-- | Get the commodity symbols used in a posting's amounts (not including costs).
postingCommodities :: Posting -> [CommoditySymbol]
postingCommodities = map acommodity . filter (not . isMissingAmount) . amountsRaw . pamount
  where isMissingAmount a = acommodity a == "AUTO"

-- | Tags for this posting including any inherited from its parent transaction.
postingAllTags :: Posting -> [Tag]
postingAllTags p = ptags p ++ maybe [] ttags (ptransaction p)

-- | Tags for this transaction including any from its postings (which includes any from the postings' accounts).
transactionAllTags :: Transaction -> [Tag]
transactionAllTags t = ttags t ++ concatMap ptags (tpostings t)

-- Get the other postings from this posting's transaction.
relatedPostings :: Posting -> [Posting]
relatedPostings p@Posting{ptransaction=Just t} = filter (/= p) $ tpostings t
relatedPostings _ = []

isEmptyPosting :: Posting -> Bool
isEmptyPosting = mixedAmountLooksZero . pamount

-- | Apply some account aliases to the posting's account name, as described by accountNameApplyAliases.
-- This can fail due to a bad replacement pattern in a regular expression alias.
postingApplyAliases :: [AccountAlias] -> Posting -> Either RegexError Posting
postingApplyAliases aliases p@Posting{paccount} =
  case accountNameApplyAliases aliases paccount of
    Right a -> Right p{paccount=a}
    Left e  -> Left err
      where
        err = "problem while applying account aliases:\n" ++ pshow aliases
          ++ "\n to account name: "++T.unpack paccount++"\n "++e

-- | Add tags to a posting, discarding any for which the posting already has a value.
-- Note this does not add tags to the posting's comment.
postingAddTags :: Posting -> [Tag] -> Posting
postingAddTags p@Posting{ptags} tags = p{ptags=ptags `union` tags}

-- | Add the given hidden tag to a posting; and with a true argument,
-- also add the equivalent visible tag to the posting's tags and comment fields.
-- If the posting already has these tags (with any value), do nothing.
postingAddHiddenAndMaybeVisibleTag :: Bool -> Bool -> HiddenTag -> Posting -> Posting
postingAddHiddenAndMaybeVisibleTag prepend verbosetags ht p@Posting{pcomment=c, ptags} =
  (p `postingAddTags` ([ht] <> [vt |verbosetags]))
  {pcomment=if verbosetags && not hadtag then addFn c vt else c}
  where
    addFn = if prepend then commentPrependTag else commentAddTag
    vt@(vname,_) = toVisibleTag ht
    hadtag = any ((== (T.toLower vname)) . T.toLower . fst) ptags  -- XXX should regex-quote vname

-- | Apply a specified valuation to this posting's amount, using the
-- provided price oracle, commodity styles, and reference dates.
-- See amountApplyValuation.
postingApplyValuation :: PriceOracle -> M.Map CommoditySymbol AmountStyle -> Day -> Day -> ValuationType -> Posting -> Posting
postingApplyValuation priceoracle styles periodlast today v p =
    postingTransformAmount (mixedAmountApplyValuation priceoracle styles periodlast today (postingDate p) v) p

-- | Maybe convert this 'Posting's amount to cost.
postingToCost :: ConversionOp -> Posting -> Maybe Posting
postingToCost NoConversionOp p = Just p
postingToCost ToCost         p
  -- If this is an equity conversion posting with an associated cost nearby, ignore it
  | conversionPostingTagName `elem` map fst (ptags p) && nocosts = Nothing
  | otherwise = Just $ postingTransformAmount mixedAmountCost p
  where
    nocosts = (not . any (isJust . acost) . amountsRaw) $ pamount p

-- | Generate equity conversion postings corresponding to a 'Posting''s cost(s)
-- (one pair of conversion postings per cost), wherever they don't already exist.
postingAddInferredEquityPostings :: Bool -> Text -> Posting -> [Posting]
postingAddInferredEquityPostings verbosetags equityAcct p
  -- this posting has no costs
  | null costs = [p]
  -- this posting is already tagged as having associated conversion postings
  | costPostingTagName `elem` map fst (ptags p) = [p]
  -- tag the posting, and for each of its costs, add an equivalent pair of conversion postings after it
  | otherwise =
    postingAddHiddenAndMaybeVisibleTag False verbosetags (costPostingTagName,"") p :
    concatMap makeConversionPostings costs
  where
    costs = filter (isJust . acost) . amountsRaw $ pamount p
    makeConversionPostings amt = case acost amt of
      Nothing -> []
      Just _  -> [ convp{ paccount = accountPrefix <> amtCommodity
                        , pamount = mixedAmount . negate $ stripBasis $ amountStripCost amt
                        }
                 , convp{ paccount = accountPrefix <> costCommodity
                        , pamount = mixedAmount cost
                        }
                 ]
      where
        cost = amountCost amt
        stripBasis a = a{acostbasis = Nothing}
        amtCommodity  = commodity amt
        costCommodity = commodity cost
        convp = nullposting{pdate=pdate p, pdate2=pdate2 p, pstatus=pstatus p, ptransaction=ptransaction p}
          & postingAddHiddenAndMaybeVisibleTag False verbosetags (conversionPostingTagName,"")
          & postingAddHiddenAndMaybeVisibleTag False verbosetags (generatedPostingTagName, "")
        accountPrefix = mconcat [ equityAcct, ":", T.intercalate "-" $ sort [amtCommodity, costCommodity], ":"]
        -- Take the commodity of an amount and collapse consecutive spaces to a single space
        commodity = T.unwords . filter (not . T.null) . T.words . acommodity

-- | Make a market price equivalent to this posting's amount's unit
-- price, if any.
postingPriceDirectivesFromCost :: Posting -> [PriceDirective]
postingPriceDirectivesFromCost p@Posting{pamount} =
    mapMaybe (amountPriceDirectiveFromCost $ postingDate p) $ amountsRaw pamount

-- | Apply a transform function to this posting's main amount (but not its balance assertion amount).
postingTransformAmount :: (MixedAmount -> MixedAmount) -> Posting -> Posting
postingTransformAmount f p@Posting{pamount=a} = p{pamount=f a}

-- | Join two parts of a comment, eg a tag and another tag, or a tag
-- and a non-tag, on a single line. Interpolates a comma and space
-- unless one of the parts is empty.
commentJoin :: Text -> Text -> Text
commentJoin c1 c2
  | T.null c1 = c2
  | T.null c2 = c1
  | otherwise = c1 <> ", " <> c2

-- | Add a tag to a comment, comma-separated from any prior content.
-- A space is inserted following the colon, before the value.
commentAddTag :: Text -> Tag -> Text
commentAddTag c (t,v)
  | T.null c' = tag
  | otherwise = c' `commentJoin` tag
  where
    c'  = T.stripEnd c
    tag = t <> ": " <> v

-- | Add a tag at the start of a comment, comma-separated from any prior content.
-- A space is inserted following the colon, before the value.
commentPrependTag :: Text -> Tag -> Text
commentPrependTag c (t,v)
  | T.null c' = tag
  | otherwise = tag `commentJoin` c'
  where
    c'  = T.stripEnd c
    tag = t <> ": " <> v

-- | Like commentAddTag, but omits the space after the colon.
commentAddTagUnspaced :: Text -> Tag -> Text
commentAddTagUnspaced c (t,v)
  | T.null c' = tag
  | otherwise = c' `commentJoin` tag
  where
    c'  = T.stripEnd c
    tag = t <> ":" <> v

-- | Add a tag on its own line to a comment, preserving any prior content.
-- A space is inserted following the colon, before the value.
commentAddTagNextLine :: Text -> Tag -> Text
commentAddTagNextLine cmt (t,v) =
  cmt <> (if "\n" `T.isSuffixOf` cmt then "" else "\n") <> t <> ": " <> v


-- tests

tests_Posting = testGroup "Posting" [

  testCase "accountNamePostingType" $ do
    accountNamePostingType "a" @?= RealPosting
    accountNamePostingType "(a)" @?= VirtualPosting
    accountNamePostingType "[a]" @?= BalancedVirtualPosting

 ,testCase "accountNameWithoutPostingType" $ do
    accountNameWithoutPostingType "(a)" @?= "a"

 ,testCase "accountNameWithPostingType" $ do
    accountNameWithPostingType VirtualPosting "[a]" @?= "(a)"

 ,testCase "joinAccountNames" $ do
    "a" `joinAccountNames` "b:c" @?= "a:b:c"
    "a" `joinAccountNames` "(b:c)" @?= "(a:b:c)"
    "[a]" `joinAccountNames` "(b:c)" @?= "[a:b:c]"
    "" `joinAccountNames` "a" @?= "a"

 ,testCase "concatAccountNames" $ do
    concatAccountNames [] @?= ""
    concatAccountNames ["a","(b)","[c:d]"] @?= "(a:b:c:d)"

 ,testCase "commentAddTag" $ do
    commentAddTag "" ("a","") @?= "a: "
    commentAddTag "[1/2]" ("a","") @?= "[1/2], a: "

 ,testCase "commentAddTagNextLine" $ do
    commentAddTagNextLine "" ("a","") @?= "\na: "
    commentAddTagNextLine "[1/2]" ("a","") @?= "[1/2]\na: "

 ]

