name:          hledger
version: 1.43.99
license:       GPL-3.0-or-later
maintainer:    Simon Michael <simon@joyful.com>
author:        Simon Michael <simon@joyful.com>
stability:     stable
tested-with:   ghc==8.10.7, ghc==9.0.2, ghc==9.2.8, ghc==9.4.8, ghc==9.6.7, ghc==9.8.4, ghc==9.10.2, ghc==9.12.1
homepage:      http://hledger.org
bug-reports:   http://bugs.hledger.org
github:        simonmichael/hledger
category:      Finance, Console
synopsis:      Command-line interface for the hledger accounting system
description: |
  The command-line interface for the hledger accounting system.
  Its basic function is to read a plain text file describing
  financial transactions and produce useful reports.

  hledger is a robust, cross-platform set of tools for tracking money,
  time, or any other commodity, using double-entry accounting and a
  simple, editable file format, with command-line, terminal and web
  interfaces. It is a Haskell rewrite of Ledger, and one of the leading
  implementations of Plain Text Accounting. Read more at:
  <https://hledger.org>

extra-source-files:
- CHANGES.md
- README.md
- bench/10000x1000x10.journal
- shell-completion/hledger-completion.bash
- test/unittest.hs

- embeddedfiles/add.cast
- embeddedfiles/balance.cast
- embeddedfiles/install.cast
- embeddedfiles/print.cast

- embeddedfiles/hledger-accounts.md
- embeddedfiles/hledger-add.md
- embeddedfiles/hledger-aregister.md
- embeddedfiles/hledger-balance.md
- embeddedfiles/hledger-balancesheet.md
- embeddedfiles/hledger-import.md
- embeddedfiles/hledger-incomestatement.md
- embeddedfiles/hledger-print.md
- embeddedfiles/hledger-ui.md
- embeddedfiles/hledger-web.md
- embeddedfiles/hledger.md

- embeddedfiles/hledger.1
- embeddedfiles/hledger.txt
- embeddedfiles/hledger.info
- embeddedfiles/hledger-ui.1
- embeddedfiles/hledger-ui.txt
- embeddedfiles/hledger-ui.info
- embeddedfiles/hledger-web.1
- embeddedfiles/hledger-web.txt
- embeddedfiles/hledger-web.info

- Hledger/Cli/Commands/Accounts.txt
- Hledger/Cli/Commands/Activity.txt
- Hledger/Cli/Commands/Add.txt
- Hledger/Cli/Commands/Aregister.txt
- Hledger/Cli/Commands/Balance.txt
- Hledger/Cli/Commands/Balancesheet.txt
- Hledger/Cli/Commands/Balancesheetequity.txt
- Hledger/Cli/Commands/Cashflow.txt
- Hledger/Cli/Commands/Check.txt
- Hledger/Cli/Commands/Close.txt
- Hledger/Cli/Commands/Codes.txt
- Hledger/Cli/Commands/Commands.txt
- Hledger/Cli/Commands/Commodities.txt
- Hledger/Cli/Commands/Demo.txt
- Hledger/Cli/Commands/Descriptions.txt
- Hledger/Cli/Commands/Diff.txt
- Hledger/Cli/Commands/Files.txt
- Hledger/Cli/Commands/Help.txt
- Hledger/Cli/Commands/Import.txt
- Hledger/Cli/Commands/Incomestatement.txt
- Hledger/Cli/Commands/Notes.txt
- Hledger/Cli/Commands/Payees.txt
- Hledger/Cli/Commands/Prices.txt
- Hledger/Cli/Commands/Print.txt
- Hledger/Cli/Commands/Register.txt
- Hledger/Cli/Commands/Rewrite.txt
- Hledger/Cli/Commands/Repl.txt
- Hledger/Cli/Commands/Roi.txt
- Hledger/Cli/Commands/Run.txt
- Hledger/Cli/Commands/Setup.txt
- Hledger/Cli/Commands/Stats.txt
- Hledger/Cli/Commands/Tags.txt
- Hledger/Cli/Commands/Test.txt

flags:
  threaded:
    description: Build with support for multithreaded execution
    default: true
    manual:  false
  debug:
    description: Build with GHC 9.10+'s stack traces enabled
    default: false
    manual:  true
#  ghcdebug:
#    description: Build with support for attaching a ghc-debug client
#    default: false
#    manual:  true

ghc-options:
- -Wall
- -Wno-incomplete-uni-patterns
- -Wno-missing-signatures
- -Wno-orphans
- -Wno-type-defaults
- -Wno-unused-do-bind
# avoid stack's "non-portable path" warning/error on mac, https://github.com/commercialhaskell/stack/issues/3918
- -optP-Wno-nonportable-include-path

when:
- condition: (flag(debug))
  cpp-options: -DDEBUG
# - condition: (flag(ghcdebug))
#   cpp-options: -DGHCDEBUG
#   dependencies:
#   - ghc-debug-stub >=0.6.0.0 && <0.7

dependencies:
- base >=4.14 && <4.22
- hledger-lib >=1.43.99 && <1.44
- aeson >=1 && <2.3
- ansi-terminal >=0.9
- bytestring
- cmdargs >=0.10
- containers >=0.5.9
- data-default >=0.5
- Decimal >=0.5.1
- directory
- extra >=1.7.11
- filepath
- githash >=0.1.6.2
- haskeline >=0.6
- http-client
- http-types
- megaparsec >=7.0.0 && <9.8
- microlens >=0.4
- mtl >=2.2.1
- process
- regex-tdfa
- req
- safe >=0.3.20
- shakespeare >=2.0.2.2
- split >=0.1
- math-functions >=0.3.3.0
- tabular >=0.2
- tasty >=1.2.3
- temporary
- text >=1.2.4.1
- text-ansi >=0.2.1
- time >=1.5
- timeit
- transformers
- unordered-containers
- utf8-string >=0.3.5
- utility-ht >=0.0.13
- wizards >=1.0

library:
  cpp-options: -DVERSION="1.43.99"
  exposed-modules:
  - Hledger.Cli
  - Hledger.Cli.Anchor
  - Hledger.Cli.Anon
  - Hledger.Cli.CliOptions
  - Hledger.Cli.Commands
  - Hledger.Cli.Commands.Accounts
  - Hledger.Cli.Commands.Activity
  - Hledger.Cli.Commands.Add
  - Hledger.Cli.Commands.Aregister
  - Hledger.Cli.Commands.Balance
  - Hledger.Cli.Commands.Balancesheet
  - Hledger.Cli.Commands.Balancesheetequity
  - Hledger.Cli.Commands.Cashflow
  - Hledger.Cli.Commands.Check
  - Hledger.Cli.Commands.Close
  - Hledger.Cli.Commands.Codes
  - Hledger.Cli.Commands.Commodities
  - Hledger.Cli.Commands.Demo
  - Hledger.Cli.Commands.Descriptions
  - Hledger.Cli.Commands.Diff
  - Hledger.Cli.Commands.Help
  - Hledger.Cli.Commands.Files
  - Hledger.Cli.Commands.Import
  - Hledger.Cli.Commands.Incomestatement
  - Hledger.Cli.Commands.Notes
  - Hledger.Cli.Commands.Payees
  - Hledger.Cli.Commands.Prices
  - Hledger.Cli.Commands.Print
  - Hledger.Cli.Commands.Register
  - Hledger.Cli.Commands.Rewrite
  - Hledger.Cli.Commands.Roi
  - Hledger.Cli.Commands.Run
  - Hledger.Cli.Commands.Setup
  - Hledger.Cli.Commands.Stats
  - Hledger.Cli.Commands.Tags
  - Hledger.Cli.CompoundBalanceCommand
  - Hledger.Cli.Conf
  - Hledger.Cli.DocFiles
  - Hledger.Cli.Script
  - Hledger.Cli.Utils
  - Hledger.Cli.Version
  dependencies:
  - Diff >=0.2
  - hashable >=1.2.4
  - lucid
  - modern-uri >=0.3

executables:
  hledger:
    source-dirs: app
    main: hledger-cli.hs
    cpp-options: -DVERSION="1.43.99"
    ghc-options: -with-rtsopts=-T  # for stats command
    when:
    - condition: flag(threaded)
      ghc-options: -threaded
    dependencies:
    - hledger

tests:
  unittest:
    source-dirs: test
    main: unittest.hs
    other-modules: []  # prevent double compilation, https://github.com/sol/hpack/issues/188
    cpp-options: -DVERSION="1.43.99"
    dependencies:
    - hledger

benchmarks:
  bench:
    buildable: false
    source-dirs: bench
    main: bench.hs
    other-modules: []  # prevent double compilation, https://github.com/sol/hpack/issues/188
    dependencies:
    - hledger
    - criterion
    - html
