name: hledger
version: '1.4.99'
synopsis: Command-line interface for the hledger accounting tool
description: |
  This is hledger's command-line interface.
  Its basic function is to read a plain text file describing
  financial transactions and produce useful reports.

  hledger is a cross-platform program for tracking money, time, or
  any other commodity, using double-entry accounting and a simple,
  editable file format. It is inspired by and largely compatible
  with ledger(1).  hledger provides command-line, curses and web
  interfaces, and aims to be a reliable, practical tool for daily
  use.
category: Finance, Console
license: GPL-3
author: Simon Michael <simon@joyful.com>
maintainer: Simon Michael <simon@joyful.com>
github: simonmichael/hledger
homepage: http://hledger.org
bug-reports: http://bugs.hledger.org
stability: stable
tested-with: GHC==7.10.3, GHC==8.0.2, GHC==8.2.1

extra-source-files:
- CHANGES
- README.md
- test/test.hs
- bench/10000x1000x10.journal

data-files:
- hledger.1
- hledger.txt
- hledger.info
- .otherdocs/hledger-api.1
- .otherdocs/hledger-api.txt
- .otherdocs/hledger-api.info
- .otherdocs/hledger-ui.1
- .otherdocs/hledger-ui.txt
- .otherdocs/hledger-ui.info
- .otherdocs/hledger-web.1
- .otherdocs/hledger-web.txt
- .otherdocs/hledger-web.info
- .otherdocs/hledger_journal.5
- .otherdocs/hledger_journal.txt
- .otherdocs/hledger_journal.info
- .otherdocs/hledger_csv.5
- .otherdocs/hledger_csv.txt
- .otherdocs/hledger_csv.info
- .otherdocs/hledger_timeclock.5
- .otherdocs/hledger_timeclock.txt
- .otherdocs/hledger_timeclock.info
- .otherdocs/hledger_timedot.5
- .otherdocs/hledger_timedot.txt
- .otherdocs/hledger_timedot.info

flags:
  terminfo:
    description: On POSIX systems, build with the terminfo lib for detecting terminal width.
    manual: false
    default: true
  threaded:
    description: Build with support for multithreaded execution
    manual: false
    default: true

ghc-options:
- -Wall
- -fno-warn-unused-do-bind
- -fno-warn-name-shadowing
- -fno-warn-missing-signatures
- -fno-warn-type-defaults
- -fno-warn-orphans

dependencies:
- base >=4.8 && <5
- base-compat >=0.8.1
- ansi-terminal >= 0.6.2.3 && < 0.9
- directory
- file-embed >=0.0.10 && <0.1
- filepath
- here
- pretty-show >=1.6.4
- process
- shakespeare >=2.0.2.2 && <2.1
- temporary
- tabular >=0.2 && <0.3
- time >=1.5
- utility-ht >= 0.0.13
- hledger-lib >= 1.4.99 && < 1.5

when:
- condition: (!(os(windows))) && (flag(terminfo))
  dependencies:
  - terminfo

library:
  cpp-options: -DVERSION="1.4.99"
  exposed-modules:
  - Hledger.Cli
  - Hledger.Cli.Main
  - Hledger.Cli.CliOptions
  - Hledger.Cli.DocFiles
  - Hledger.Cli.Utils
  - Hledger.Cli.Version
  - Hledger.Cli.Commands
  - Hledger.Cli.Commands.Accounts
  - Hledger.Cli.Commands.Activity
  - Hledger.Cli.Commands.Add
  - Hledger.Cli.Commands.Balance
  - Hledger.Cli.Commands.Balancesheet
  - Hledger.Cli.Commands.Balancesheetequity
  - Hledger.Cli.Commands.Cashflow
  - Hledger.Cli.Commands.Checkdates
  - Hledger.Cli.Commands.Checkdupes
  - Hledger.Cli.Commands.Equity
  - Hledger.Cli.Commands.Help
  - Hledger.Cli.Commands.Import
  - Hledger.Cli.Commands.Incomestatement
  - Hledger.Cli.Commands.Prices
  - Hledger.Cli.Commands.Print
  - Hledger.Cli.Commands.Printunique
  - Hledger.Cli.Commands.Register
  - Hledger.Cli.Commands.Registermatch
  - Hledger.Cli.Commands.Rewrite
  - Hledger.Cli.Commands.Stats
  - Hledger.Cli.Commands.Tags
  - Hledger.Cli.CompoundBalanceCommand
  - Text.Tabular.AsciiWide
  dependencies:
  - bytestring
  - containers
  - unordered-containers
  - cmdargs >=0.10 && <0.11
  - csv
  - data-default >=0.5
  - Diff
  - hashable >=1.2.4
  - haskeline >=0.6 && <=0.8
  - HUnit
  - mtl
  - mtl-compat
  - old-time
  - megaparsec >=5.0 && < 6.5
  - regex-tdfa
  - safe >=0.2
  - split >=0.1 && <0.3
  - transformers
  - text >=0.11
  - utf8-string >=0.3.5 && <1.1
  - wizards ==1.0.*
  - Decimal

executables:
  hledger:
    source-dirs: app
    main: hledger-cli.hs
    cpp-options: -DVERSION="1.4.99"
    when:
    - condition: flag(threaded)
      ghc-options: -threaded
    dependencies:
    - hledger
    - bytestring
    - containers
    - unordered-containers
    - cmdargs >=0.10 && <0.11
    - csv
    - data-default >=0.5
    - haskeline >=0.6 && <=0.8
    - HUnit
    - mtl
    - mtl-compat
    - old-time
    - parsec >=3
    - regex-tdfa
    - safe >=0.2
    - split >=0.1 && <0.3
    - text >=0.11
    - utf8-string >=0.3.5 && <1.1
    - wizards ==1.0.*
    - Decimal

tests:
  test:
    source-dirs: test
    main: test.hs
    cpp-options: -DVERSION="1.4.99"
    dependencies:
    - hledger
    - bytestring
    - containers
    - unordered-containers
    - cmdargs >=0.10 && <0.11
    - csv
    - data-default >=0.5
    - haskeline >=0.6 && <=0.8
    - HUnit
    - mtl
    - mtl-compat
    - old-time
    - parsec >=3
    - regex-tdfa
    - safe >=0.2
    - split >=0.1 && <0.3
    - text >=0.11
    - utf8-string >=0.3.5 && <1.1
    - wizards ==1.0.*
    - Decimal
    - test-framework
    - test-framework-hunit

benchmarks:
  bench:
    source-dirs: bench
    main: bench.hs
    dependencies:
    - hledger
    - criterion
    - html
    - timeit
