name: hledger
version: '1.0'
synopsis: Command-line interface for the hledger accounting tool
description: |
  This is hledger's command-line interface.
  Its basic function is to read a plain text file describing
  financial transactions and produce useful reports.

  hledger is a cross-platform program for tracking money, time, or
  any other commodity, using double-entry accounting and a simple,
  editable file format. It is inspired by and largely compatible
  with ledger(1).  hledger provides command-line, curses and web
  interfaces, and aims to be a reliable, practical tool for daily
  use.
category: Finance, Console
license: GPL
author: Simon Michael <simon@joyful.com>
maintainer: Simon Michael <simon@joyful.com>
github: simonmichael/hledger
homepage: http://hledger.org
bug-reports: http://bugs.hledger.org
extra-source-files:
- CHANGES
- README.md
- test/test.hs
- bench/10000x1000x10.journal
data-files:
- doc/hledger.1
- doc/hledger.1.txt
- doc/hledger.1.info
- doc/other/hledger-api.1
- doc/other/hledger-api.1.txt
- doc/other/hledger-api.1.info
- doc/other/hledger-ui.1
- doc/other/hledger-ui.1.txt
- doc/other/hledger-ui.1.info
- doc/other/hledger-web.1
- doc/other/hledger-web.1.txt
- doc/other/hledger-web.1.info
- doc/other/hledger_journal.5
- doc/other/hledger_journal.5.txt
- doc/other/hledger_journal.5.info
- doc/other/hledger_csv.5
- doc/other/hledger_csv.5.txt
- doc/other/hledger_csv.5.info
- doc/other/hledger_timeclock.5
- doc/other/hledger_timeclock.5.txt
- doc/other/hledger_timeclock.5.info
- doc/other/hledger_timedot.5
- doc/other/hledger_timedot.5.txt
- doc/other/hledger_timedot.5.info
flags:
  terminfo:
    description: On POSIX systems, build with the terminfo lib for detecting terminal width.
    manual: false
    default: true
  threaded:
    description: Build with support for multithreaded execution
    manual: false
    default: true
  oldtime:
    description: If building with time < 1.5, also depend on old-locale. Set automatically by cabal.
    manual: false
    default: false
dependencies:
- base >=4.3 && <5
- base-compat >=0.8.1
- directory
- file-embed >=0.0.10 && <0.1
- filepath
- pretty-show >=1.6.4
- process
- temporary
- tabular >=0.2 && <0.3
ghc-options:
- -Wall
- -fno-warn-unused-do-bind
- -fno-warn-name-shadowing
- -fno-warn-missing-signatures
- -fno-warn-type-defaults
- -fno-warn-orphans
library:
  cpp-options: -DVERSION="1.0"
  exposed-modules:
  - Hledger.Cli
  - Hledger.Cli.Main
  - Hledger.Cli.CliOptions
  - Hledger.Cli.DocFiles
  - Hledger.Cli.Tests
  - Hledger.Cli.Utils
  - Hledger.Cli.Version
  - Hledger.Cli.Add
  - Hledger.Cli.Accounts
  - Hledger.Cli.Balance
  - Hledger.Cli.Balancesheet
  - Hledger.Cli.Cashflow
  - Hledger.Cli.Help
  - Hledger.Cli.Histogram
  - Hledger.Cli.Incomestatement
  - Hledger.Cli.Info
  - Hledger.Cli.Man
  - Hledger.Cli.Print
  - Hledger.Cli.Register
  - Hledger.Cli.Stats
  - Text.Tabular.AsciiWide
  dependencies:
  - hledger-lib ==1.0
  - bytestring
  - containers
  - unordered-containers
  - cmdargs >=0.10 && <0.11
  - csv
  - data-default >=0.5
  - hashable >=1.2.4
  - haskeline >=0.6 && <=0.8
  - HUnit
  - mtl
  - mtl-compat
  - old-time
  - megaparsec >=5 && < 5.1
  - regex-tdfa
  - safe >=0.2
  - split >=0.1 && <0.3
  - transformers
  - text >=0.11
  - utf8-string >=0.3.5 && <1.1
  - wizards ==1.0.*
  when:
  - condition: impl(ghc <7.6)
    dependencies:
    - ghc-prim
  - condition: impl(ghc >=7.10)
    then:
      dependencies:
      - shakespeare >=2.0.2.2 && <2.1
    else:
      dependencies:
      - shakespeare >=1.0 && <2.1
      - shakespeare-text >=1.0 && <1.2
  - condition: flag(oldtime)
    then:
      dependencies:
      - time <1.5
      - old-locale
    else:
      dependencies:
      - time >=1.5
  - condition: (!(os(windows))) && (flag(terminfo))
    dependencies:
    - terminfo
executables:
  hledger:
    main: hledger-cli.hs
    source-dirs: app
    cpp-options: -DVERSION="1.0"
    dependencies:
    - hledger-lib >= 1.0 && < 1.1
    - hledger >= 1.0 && < 1.1
    - bytestring
    - containers
    - unordered-containers
    - cmdargs >=0.10 && <0.11
    - csv
    - data-default >=0.5
    - haskeline >=0.6 && <=0.8
    - HUnit
    - mtl
    - mtl-compat
    - old-time
    - parsec >=3
    - regex-tdfa
    - safe >=0.2
    - split >=0.1 && <0.3
    - text >=0.11
    - utf8-string >=0.3.5 && <1.1
    - wizards ==1.0.*
    when:
    - condition: flag(threaded)
      ghc-options: -threaded
    - condition: impl(ghc <7.6)
      dependencies:
      - ghc-prim
    - condition: impl(ghc >=7.10)
      then:
        dependencies:
        - shakespeare >=2.0.2.2 && <2.1
      else:
        dependencies:
        - shakespeare >=1.0 && <2.1
        - shakespeare-text >=1.0 && <1.2
    - condition: flag(oldtime)
      then:
        dependencies:
        - time <1.5
        - oldtime
      else:
        dependencies:
        - time >=1.5
    - condition: (!(os(windows))) && (flag(terminfo))
      dependencies:
      - terminfo
tests:
  test:
    main: test.hs
    source-dirs: test
    cpp-options: -DVERSION="1.0"
    dependencies:
    - hledger-lib ==1.0
    - hledger
    - bytestring
    - containers
    - unordered-containers
    - cmdargs >=0.10 && <0.11
    - csv
    - data-default >=0.5
    - haskeline >=0.6 && <=0.8
    - HUnit
    - mtl
    - mtl-compat
    - old-time
    - parsec >=3
    - regex-tdfa
    - safe >=0.2
    - split >=0.1 && <0.3
    - text >=0.11
    - utf8-string >=0.3.5 && <1.1
    - wizards ==1.0.*
    - test-framework
    - test-framework-hunit
    when:
    - condition: impl(ghc <7.6)
      dependencies:
      - ghc-prim
    - condition: impl(ghc >=7.10)
      then:
        dependencies:
        - shakespeare >=2.0.2.2 && <2.1
      else:
        dependencies:
        - shakespeare >=1.0 && <2.1
        - shakespeare-text >=1.0 && <1.2
    - condition: flag(oldtime)
      then:
        dependencies:
        - time <1.5
        - oldtime
      else:
        dependencies:
        - time >=1.5
    - condition: (!(os(windows))) && (flag(terminfo))
      dependencies:
      - terminfo
benchmarks:
  bench:
    main: bench.hs
    source-dirs: bench
    dependencies:
    - hledger-lib
    - hledger
    - criterion
    - html
    - timeit
    when:
    - condition: flag(oldtime)
      then:
        dependencies:
        - time <1.5
        - oldtime
      else:
        dependencies:
        - time >=1.5
stability: stable
tested-with: GHC==7.10.3, GHC==8.0
