#!/usr/bin/env sh
# Execute all test journals, showing their error messages
# (as README-ready markdown).

# All test journals in this directory, in preferred test/display order
testfiles="\
  parseable.j \
  parseable-dates.j \
  parseable-regexps.j \
  balanced.j \
  balancednoautoconversion.j \
  assertions.j \
  accounts.j \
  commodities.j \
  payees.j \
  ordereddates.j \
  uniqueleafnames.j \
  "

printf '%s error messages, last updated %s:\n\n' \
       "$(hledger --version | cut -d, -f1)" \
       "$(date +%Y-%m-%d)"

for f in $testfiles; do
    printf '### %s\n```\n' "$(echo "$f" | cut -d. -f1)"
    ./"$f" || true
    printf '```\n\n'
done
