name: hledger-web
version: '1.9.99'
synopsis: Web interface for the hledger accounting tool
description: |
  This is hledger's web interface.
  It provides a more user-friendly and collaborative UI than the
  command-line or curses-style interfaces.

  hledger is a cross-platform program for tracking money, time, or
  any other commodity, using double-entry accounting and a simple,
  editable file format. It is inspired by and largely compatible
  with ledger(1).  hledger provides command-line, curses and web
  interfaces, and aims to be a reliable, practical tool for daily
  use.
category: Finance
license: GPL-3
author: Simon Michael <simon@joyful.com>
maintainer: Simon Michael <simon@joyful.com>
github: simonmichael/hledger
homepage: http://hledger.org
bug-reports: http://bugs.hledger.org
stability: stable
tested-with: GHC==7.10.3, GHC==8.0.2, GHC==8.2.2, GHC==8.4.1

extra-source-files:
- CHANGES
- README
- config/favicon.ico
- config/keter.yaml
- config/robots.txt
- config/routes
- config/settings.yml
- messages/*.msg
- static/css/*.css
- static/css/*.map
- static/fonts/*.eot
- static/fonts/*.svg
- static/fonts/*.ttf
- static/fonts/*.woff
- static/hledger.css
- static/hledger.js
- static/js/*.js
- templates/*.hamlet
- hledger-web.1
- hledger-web.txt
- hledger-web.info

#data-files:

flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
  threaded:
    description: Build with support for multithreaded execution.
    manual: false
    default: true

dependencies:
- hledger-lib >=1.9.99 && <2.0
- hledger >=1.9.99 && <2.0
- base >=4.8 && <4.12
- base-compat >=0.8.1
- blaze-html
- blaze-markup
- bytestring
- clientsession
- cmdargs >=0.10
- data-default
- directory
- filepath
- hjsmin
- http-conduit
- http-client
- HUnit
- conduit-extra >=1.1
- safe >=0.2
- shakespeare >=2.0.2.2
- template-haskell
- text >=1.2
- time >=1.5
- transformers
- wai
- wai-extra
- wai-handler-launch >=1.3
- warp
- yaml
- yesod        >=1.4 && < 1.7
- yesod-core   >=1.4 && < 1.7
- yesod-form   >=1.4 && < 1.7
- yesod-static >=1.4 && < 1.7
- json
- megaparsec >=6.4.1
- mtl
- parsec >=3

when:
- condition: (flag(dev)) || (flag(library-only))
  cpp-options: -DDEVELOPMENT
- condition: flag(dev)
  ghc-options: -O0

ghc-options:
- -Wall
- -fno-warn-unused-do-bind
- -fno-warn-name-shadowing
- -fno-warn-missing-signatures
- -fno-warn-type-defaults
- -fno-warn-orphans

library:
  cpp-options: -DVERSION="1.9.99"
  exposed-modules:
  - Application
  - Foundation
  - Handler.AddForm
  - Handler.Common
  - Handler.JournalR
  - Handler.RegisterR
  - Handler.RootR
  - Handler.SidebarR
  - Handler.Utils
  - Hledger.Web
  - Hledger.Web.Main
  - Hledger.Web.WebOptions
  - Import
  - Settings
  - Settings.Development
  - Settings.StaticFiles

executables:
  hledger-web:
    source-dirs: app
    main: main.hs
    cpp-options: -DVERSION="1.9.99"
    dependencies:
    - hledger-web
    when:
    - condition: flag(library-only)
      buildable: false
    - condition: flag(threaded)
      ghc-options: -threaded

tests:
  test:
    source-dirs: tests
    main: main.hs
    cpp-options: -DVERSION="1.9.99"
    dependencies:
    - hledger-web
    - hspec
    - yesod-test
