name:          hledger-web
version:       1.42.99
license:       GPL-3.0-or-later
maintainer:    Simon Michael <simon@joyful.com>
author:        Simon Michael <simon@joyful.com>
stability:     stable
tested-with:   ghc==8.10.7, ghc==9.0.2, ghc==9.2.8, ghc==9.4.8, ghc==9.6.7, ghc==9.8.4, ghc==9.10.1
homepage:      http://hledger.org
bug-reports:   http://bugs.hledger.org
github:        simonmichael/hledger
category:      Finance
synopsis:      Web user interface for the hledger accounting system
description: |
  A simple web user interface for the hledger accounting system,
  providing a more modern UI than the command-line or terminal interfaces.
  It can be used as a local single-user UI, or as a multi-user UI for
  viewing\/adding\/editing on the web.

  hledger is a robust, cross-platform set of tools for tracking money,
  time, or any other commodity, using double-entry accounting and a
  simple, editable file format, with command-line, terminal and web
  interfaces. It is a Haskell rewrite of Ledger, and one of the leading
  implementations of Plain Text Accounting. Read more at:
  <https://hledger.org>

extra-source-files:
- CHANGES.md
- README.md
- config/favicon.ico
- config/keter.yaml
- config/robots.txt
- config/routes
- config/settings.yml
- static/css/*.css
- static/css/*.map
- static/fonts/*.eot
- static/fonts/*.svg
- static/fonts/*.ttf
- static/fonts/*.woff
- static/hledger.css
- static/hledger.js
- static/js/*.js
- templates/*.hamlet
- hledger-web.1
- hledger-web.txt
- hledger-web.info

flags:
  library-only:
    description: Build for use with "yesod devel"
    default: false
    manual:  false
  dev:
    description: Turn on development settings, like auto-reload templates.
    default: false
    manual:  false
  threaded:
    description: Build with support for multithreaded execution.
    default: true
    manual:  false
  debug:
    description: Build with GHC 9.10+'s stack traces enabled   # '
    default: false
    manual:  true
#  ghcdebug:
#    description: Build with support for attaching a ghc-debug client
#    default: false
#    manual:  true

ghc-options:
- -Wall
# not included in -Wall:
- -Wredundant-constraints
# not included in -Wall by older GHC versions:
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns

when:
- condition: flag(threaded)
  ghc-options: -threaded
- condition: (flag(dev)) || (flag(library-only))
  cpp-options: -DDEVELOPMENT
# This causes a warning when uploading to hackage:
#Package check reported the following warnings:
# 'ghc-options: -O0' is not needed. Use the --disable-optimization configure flag.
- condition: flag(dev)
  ghc-options: -O0
- condition: (flag(debug))
  cpp-options: -DDEBUG
# - condition: (flag(ghcdebug))
#   cpp-options: -DGHCDEBUG
#   dependencies:
#   - ghc-debug-stub >=0.6.0.0 && <0.7

dependencies:
- base >=4.14 && <4.22

library:
  source-dirs: .
  cpp-options: -DVERSION="1.42.99"
  exposed-modules:
  - Hledger.Web
  - Hledger.Web.Main
  - Hledger.Web.WebOptions
  - Hledger.Web.Application
  - Hledger.Web.Import
  - Hledger.Web.Test
  dependencies:
  - hledger-lib >=1.42.99 && <1.43
  - hledger >=1.42.99 && <1.43
  - aeson >=1 && <2.3
  - base64
  - blaze-html
  - blaze-markup
  - bytestring
  - case-insensitive
  - clientsession
  - cmdargs >=0.10
  - conduit
  - conduit-extra >=1.1
  - containers >=0.5.9
  - data-default
  - Decimal >=0.5.1
  - directory >=1.2.3.0
  - extra >=1.7.11
  - file-embed >=0.0.16.0
  - filepath
  - githash >=0.1.6.2
  - hjsmin
  - http-conduit
  - http-client
  - http-types
  - megaparsec >=7.0.0 && <9.8
  - mtl >=2.2.1
  - network
  - safe >=0.3.20
  - shakespeare >=2.0.2.2
  - template-haskell
  - text >=1.2.4.1
  - time >=1.5
  - transformers
  - unix-compat
  - unordered-containers
  - utf8-string
  - wai
  - wai-extra
  - wai-handler-launch >=3.0.3
  - wai-cors
  - warp
  - yaml
  - yesod        >=1.4 && < 1.7
  - yesod-core   >=1.4 && < 1.7
  - yesod-form   >=1.4 && < 1.8
  - yesod-static >=1.4 && < 1.7
  - hspec
  - yesod-test

executables:
  hledger-web:
    source-dirs: app
    main: main.hs
    cpp-options: -DVERSION="1.42.99"
    ghc-options: -with-rtsopts=-T  # for stats command
    dependencies:
    - hledger-web
    when:
    - condition: flag(library-only)
      buildable: false

tests:
  test:
    source-dirs: test
    main: test.hs
    other-modules: []  # prevent double compilation, https://github.com/sol/hpack/issues/188
    cpp-options: -DVERSION="1.42.99"
    dependencies:
    - hledger-web
    # - hspec
    # - text
    # - yesod
    # - yesod-test
