#!/usr/bin/env bash
# regen - regenerate shell tests from the ledger files found under this directory

set -e
find . -name "*.journal" \
     -o -name "*.j" \
     -o -name "*.ledger" \
     -o -name "*.test" \
| perl -p -e 's/^\.\///' \
| perl -p -e 's/^/\$ hledger codes >\/dev\/null -f /' \
| sort \
> ledgerfiles.shelltest

# hledger codes is just a cheap command to run
