#!/usr/bin/env bash
# Try to read all .test files, save and report the results.

set -e
FILES=$(find . -name "*.j" -o -name "*.test")
#FILES=$(find . -name "*.j")

for f in $FILES ; do
    printf ":%s: " "$f"
    (hledger -f "$f" stats >/dev/null && echo ok) || echo fail
    # (hledger -f "$f" stats >/dev/null 2>&1 && echo ok) || echo fail
    # printf "." 1>&2
done 2>&1 | tee log
echo
echo "tested on $(date +%Y-%m-%d) with $(hledger --version)"
cp log log."$(date +%Y%m%d)"
./summary
