#!/usr/bin/env bash
# Summarise the results of the last test run
set -e
printf "test files: %4d\n" "$(rg -c '^:'          log || echo 0)"
printf "success:    %4d\n" "$(rg -c ': ok$'       log || echo 0)"
printf "failure:    %4d\n" "$(rg -c '(^|: )fail$' log || echo 0)"
