#!/usr/bin/env bash
# run all the ledger compatibility tests and log the results as an org file

set -e
mkdir -p log
time \
    (shelltest collected baseline regress --execdir -j8 --hide-successes; \
     echo ":Summary"; ) | tee log/latest
(echo "* Tested $(date +%Y-%m-%d) with $(hledger --version)"; \
 echo "** failures") >log/latest.org
perl -p -e 's/^:/*** ..\//' log/latest >>log/latest.org  # ../ for easy ffap
cp log/latest.org log/"$(date +%Y%m%d)".org
