#!/usr/bin/env bash
# pushdocs [MSG] - commit manuals with ";doc: MSG" prefix, push to CI, then to master

set -e

MSG=";doc: $1"

DOCS=(hledger/hledger.m4.md hledger-ui/hledger-ui.m4.md hledger-web/hledger-web.m4.md)

git commit -uno -m "$MSG" "${DOCS[@]}" hledger-web/hledger-web.m4.md || true
push \
&& printf "Docs should be up to date momentarily:\n\
\n\
https://hledger.org/dev/hledger.html\n\
https://hledger.org/dev/hledger-ui.html\n\
https://hledger.org/dev/hledger-web.html\n\
"
